### ISSUE TITLE
Add a librsync

### ISSUE THREAD

**Issue by szdytom** [WayneD/rsync#106]
**Issue Type:** Feature Request
**Discription:**
I am trying to use rsync in my C++ code, it seem that there is only one way of using it like:
```cpp
system("rsync -r rsync://jack@123.45.67.89/modules .");
```

This is not beautiful(can may cause command-line injections), I wonder if there can be a _librsync_ empowering us to use it like:
```cpp
#inlude <rsync/core.h>
sync_directory("rsync://123.45.67.89/modules", ".", rsync_auth("jack", "123456"));
```

or is there already some api like this but I don't know?

**Comment by WayneD** [comment]
Some other people may have done some work on their own API code, but nothing official.  I personally have no desire to write any such thing.  Whenever I've needed some programmatic rsync copying I always launch a real rsync using a safe exec method (one that does not launch a shell), make sure that `--protect-args` and `--itemize-changes` are specified, and parse the itemized output.
