### ISSUE TITLE
FreeBSD help-from-md issue

### ISSUE THREAD

**Issue by benrubson** [WayneD/rsync#11]
Hi,

On FreeBSD, with `3.2.0pre2`, `make` leads to the following issue :
```
./help-from-md "./" help-rsync.h
Discarding empty output for help-rsync.h file from ./
*** Error code 1

Stop.
```

Trying to figure-out why.

Thx 👍

**Comment by WayneD** [comment]
Please give the latest version a try:

https://raw.githubusercontent.com/WayneD/rsync/master/help-from-md

Thanks for the report!

**Comment by WayneD** [comment]
I went ahead and just turned help-from-md into an awk script. The latest master branch has help-from-md.awk and a tweaked Makefile.in to call it.

**Comment by benrubson** [comment]
Thank you Wayne.
Unfortunately there must be another issue :|
```
awk -f ./help-from-md.awk -v helpfile=help-rsync.h ./
Failed to find help-rsync.h section in ./
*** Error code 1

Stop.
```
If I switch to `gawk` :
```
gawk -f ./help-from-md.awk -v helpfile=help-rsync.h ./
gawk: ./help-from-md.awk:11: warning: command line argument `./' is a directory: skipped
Failed to find help-rsync.h section in ./
*** Error code 1

Stop.
```
An argument issue ?

**Comment by WayneD** [comment]
It kinda looks like BSD make doesn't support `$<` (or maybe it didn't like `$(srcdir)/$<` which should not have actually had the srcdir qualification).  In any case I've just changed a few instances of `$<` in the makefile for the actual src file.

**Comment by benrubson** [comment]
Does the trick, thank you Wayne 👍
