### ISSUE TITLE
mute `skipping non-regular file` when executed with --no-specials and/or --no-devices

### ISSUE THREAD

**Issue by kucharskim** [WayneD/rsync#111]
Could rsync skip printing `skipping non-regular file` messages when `--no-specials` is in effect, or could there be a simple way (an option) to mute those warnings, when rsync is not going to sync special files anyway.

**Comment by kucharskim** [comment]
On my end here, message is printed with unix sockets, named pipes, character and block devices. I guess similar effect would be nice for `--no-devices` option (to mute `skipping non-regular file` when `--no-devices` is used for bock and character devices). I'm executing rsync with `-rvaH --inplace --numeric-ids --no-specials --no-devices --delete-during --delete-excluded`, if that helps.

**Comment by WayneD** [comment]
Rsync now lets you silence the messages via `--info=nonreg0`.
