### ISSUE TITLE
Bug in ./configure test for tz argument (mac with new xcode)

### ISSUE THREAD

**Issue by dmacks** [WayneD/rsync#116]
On old xcode:

checking if gettimeofday takes tz argument... yes

and building rsync succeeds. On new xcode:

checking if gettimeofday takes tz argument... no

and building fails because gettimeofday() is called with the wrong number of arguments. Looking at config.log on old xcode:

with config.log:
```
configure.sh:8400: checking if gettimeofday takes tz argument
configure.sh:8418: gcc -c -I./zlib -Os -DHAVE_CONFIG_H -Wall -W -I/sw/include c\
onftest.c >&5
conftest.c:171:20: warning: implicitly declaring library function 'exit' with t\
ype 'void (int) __attribute__((noreturn))' [-Wimplicit-function-declaration]
struct timeval tv; exit(gettimeofday(&tv, NULL));
                   ^
conftest.c:171:20: note: include the header <stdlib.h> or explicitly provide a \
declaration for 'exit'
1 warning generated.
configure.sh:8418: $? = 0
configure.sh:8425: result: yes
```

The latest Apple compilers seem to have set -Werror by default, so this test becomes a fail instead of a pass due to the irrelevant warning in the test itself. Including stdlib.h in the compile-test for the parameters should clear the warning and give the correct test result.

**Comment by WayneD** [comment]
The latest master should have this fixed. Thanks!
