### ISSUE TITLE
Feature request: `--prefix=PREFIX` to complement `--suffix=SUFFIX`

### ISSUE THREAD

**Issue by MatanSilver** [WayneD/rsync#117]
I have searched on the current issues page as well as old github issues and didn't see anything like this so I hope this is the right place.

Using the `--suffix` flag is useful because it allows you to encode more information into the name of a backup file (like the date of backup, for example). However, because the suffix goes at the end of the filename, it interferes with the OS's ability to determine the filetype. So for example if I have an `example.xlsx` file and it gets backed up to `example.xlsx.2020-11-14` using the suffix, I can no longer open it directly without first manually adding the file extension.

Adding a prefix feature would allow you to maintain the additional information in the backup name without invalidating the file extension. For example, `example.xlsx` would become `2020-11-14-example.xlsx`.

If this is something which fits in the future of rsync but no one has time to take it on, I'd be happy to give implementing this a shot though I am unfamiliar with this codebase. Any feedback is appreciated.

**Comment by WayneD** [comment]
No need to duplicate bugzilla bugs here too.  The original bug is still open, but has a pretty low probability of being incorporated into rsync.
