### ISSUE TITLE
total size is 0  speedup is 0.00

### ISSUE THREAD

**Issue by alanhg** [WayneD/rsync#118]
I meet the error and don't know why.

All file size is 0.

![image](https://user-images.githubusercontent.com/9245110/99744265-575c3b00-2b12-11eb-9aee-a52df06c5024.png)

but on my mac, it's ok

![image](https://user-images.githubusercontent.com/9245110/99782526-3caab600-2b54-11eb-8161-1a28786c29df.png)

and when I use SCP, the issue occurs again. so I think it's not a command issue. it's ssh?

## Command

```
rsync -arvzh --delete public/ root@1991421.cn:/var/www/blog/static-html/
```

## Version Info

source os  is macOS-10.15
target os is CentOS 7 x64

**Comment by WayneD** [comment]
Since the files are size 0, so the total of all file sizes is also 0. Given that, the speedup can't be anything non-zero, since there is no content that can be used to speed anything up.
