### ISSUE TITLE
--executability is implied and cannot be turned off

### ISSUE THREAD

**Issue by tomty89** [WayneD/rsync#120]
Neither `--no-E` nor `--no-executability` can be used to turn it off while it is on by default. IMHO it should be off by default (otherwise the switch should be `--noexecutabilty`, no?).

**Comment by WayneD** [comment]
To quote the man page:

> New files get their "normal" permission bits set to the source file's permissions masked with the receiving directory's default permissions (either the receiving process's umask, or the permissions specified via the destination directory's default ACL), and their special permission bits disabled except in the case where a new directory inherits a setgid bit from its parent directory.

This is the same as what cp does.  Thus, if a file is new, execute can carry over, but if a file already exists w/o execute, that perm isn't changed w/o using `-E` or `-p`.  If you want to force execute off for all files, consider using `--chmod=Fa-x`.

**Comment by tomty89** [comment]
Why the difference though? Isn't it way more expected and straight-forward if it's a simple "subset" of -p? Why should new files be exceptions?

**Comment by WayneD** [comment]
Because that's how cp & rsync have always worked. The default combines the original mode with the umask, and that's the way it always will be. Rsync gives you the tools to override that, though.
