### ISSUE TITLE
Linux Manual Page: Update Bug Website to https

### ISSUE THREAD

**Issue by Semnodime** [WayneD/rsync#129]
http://rsync.samba.org/ -> https://rsync.samba.org/

**Comment by claell** [comment]
Not sure how this works. Is the manpage generated from the file here on GitHub? There it seems to be already https, see https://github.com/WayneD/rsync/blob/master/rsync.1.md#credits for example.

**Comment by WayneD** [comment]
I have no idea what you mean, since all the links were updated to https ages ago.

**Comment by Semnodime** [comment]
Linux Mint 20 (5.4.0-62-generic)
`apt install rsync`
`man rsync | grep http`
```
Please report bugs! See the web site at http://rsync.samba.org/
A WEB site is available at http://rsync.samba.org/.  The site includes an FAQ-O-Matic which may cover questions unanswered by this manual page.
Mailing lists for support and development are available at http://lists.samba.org
````

**Comment by claell** [comment]
I'd assume this installs a not up to date version for you, since the repositories might be a bit behind. Can you check?

**Comment by Semnodime** [comment]
`apt show rsync`
Package: rsync
Version: 3.1.3-8
Priority: standard
Section: net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Paul Slootman <paul@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 696 kB
Pre-Depends: init-system-helpers (>= 1.54~)
Depends: lsb-base, libacl1 (>= 2.2.23), libc6 (>= 2.15), libpopt0 (>= 1.14)
Suggests: openssh-client, openssh-server
Homepage: https://rsync.samba.org/
Task: standard
Download-Size: 322 kB
APT-Manual-Installed: yes
APT-Sources: http://ftp.fau.de/ubuntu focal/main amd64 Packages
Description: fast, versatile, remote (and local) file-copying tool
 rsync is a fast and versatile file-copying tool which can copy locally
 and to/from a remote host. It offers many options to control its behavior,
 and its remote-update protocol can minimize network traffic to make
 transferring updates between machines fast and efficient.
 .
 It is widely used for backups and mirroring and as an improved copy
 command for everyday use.
 .
 This package provides both the rsync command line tool and optional
 daemon functionality.

**Comment by claell** [comment]
That explains it most likely.

I digged around on that version's files to find the one for the manpage: https://github.com/WayneD/rsync/blob/v3.1.3/rsync.yo. That one still had no https. So the problem is already fixed, but your distribution has not shipped it, yet.
