### ISSUE TITLE
Please move rrsync.pl into C core

### ISSUE THREAD

**Issue by trentbuck** [WayneD/rsync#133]
I use rsync to backup embedded routers, typical total non-volatile storage 8MB.
I want to use `command="rrsync -ro /"` to lock down the backup, but that needs perl (about 2.5MB).

rrsync is really simple -- can it be translated to C and merged into rsync "proper"?
This would also do away with rrsync having to re-implement rsync's argument parser.

I imagine it would work similar to `rsync --daemon` and `rsync --server` currently do, so
something like `rsync --forced-command --read-only /`.
Alternatively, rsync could check argv[0] puts it in "rrsync mode" -- or rrsync could be an entirely separate binary that re-uses the argument parsing code from rsync.
It looks like argument parsing currently happens in main.c, so that last approach is probably not viable.

PS: sorry if this is a duplicate bug!
I couldn't find an existing WONTFIX bug for this on github or bugzilla.
I didn't check the mailing list.

**Comment by WayneD** [comment]
If you wish to rewrite it in C, you may feel free but the official version is going to remain some kind of script.  At some point it will probably be rewritten in python3.  The packaging/cull_options script generates the option data that is manually copy/pasted into the script (actually via `vim -d` to check for changes), so that script will also be updated at the same time.

**Comment by trentbuck** [comment]
Wayne Davison wrote:
> If you wish to rewrite it in C, you may feel free but the official version is going to remain some kind of script.

Fair enough.
What is the rationale for keeping rrsync a script?
So that it is easy for sysadmins to hack in local tweaks?

> At some point it will probably be rewritten in python3.  The packaging/cull_options script generates the option data that is manually copy/pasted into the script (actually via `vim -d` to check for changes), so that script will also be updated at the same time.

Thanks, I didn't know about cull_options.
That at least means nobody has to hand-write the argument parsing a second time!

The python3 footprint for my router is actually bigger than perl :-)

If I can find time, I'll try porting rrsync to python3.
Am I right in thinking you only want to use libraries that ship with cpython,
and not e.g. https://cheeseshop.python.org/project/click ?

**Comment by trentbuck** [comment]
Trent W. Buck wrote:
> If I can find time, I'll try porting rrsync to python3.

FYI I made a start but didn't get very far:
https://github.com/trentbuck/rsync/blob/python3-rrsync/packaging/cull_options.py#L121
