### ISSUE TITLE
Recursive --copy-dest

### ISSUE THREAD

**Issue by lockywolf** [WayneD/rsync#134]
Hello. Thank you for a wonderful tool! 

My use-case is the following:

I have a huge HDD with "Data dumps", that is full copies of my old laptops just dumped randomly at the disk root, at my backup server.

Later copied that HDD onto my local machine, and invested some time and effort to make everything properly arranged. Now I want to upload the "sorted out" HDD onto the remote machine (to a blank disk), and I would like to reuse the original "messy" hdd as a transfer base, because my link is rather slow. Setting '--copy-dist' saves a lot of effort for the directories already sorted, however, it is not helping with directories that look like "Old_pc/backup/I_forgot_date". 

I would like to ask that `--copy-dest` be augmented with an option to search for base files recursively. On my machine `find /base/dir` takes about 3 minutes, which is significantly less than the transfer would take.

**Comment by WayneD** [comment]
You can specify more than one copy-dest option if you like, but you need to find the directories to use for yourself.  e.g. put that find into a script and use the results to call rsync.  If the files being copied are fragmented, then limit what is being copied to just the one found base dir and call rsync multiple times.
