### ISSUE TITLE
User nobody is only meant for NFS usage

### ISSUE THREAD

**Issue by cpaelzer** [WayneD/rsync#135]
Hi,
while working on other packages in the past I learned that user "nobody" is rather special and meant for [exclusive use to NFS](https://wiki.ubuntu.com/nobody). I know it is used in many programs and places, but that doesn't make it right.
Especially if multiple programs are misconfigured to to use "nobody" they might grant way more permission (across each others data) than what is intended.

For a smooth transition configure could add a config statement allowing to set a user/group and keep the default to the current values. That would allow Distribution packagers that can control the creation of users/groups on package install to configure such a user at build time which then can be rendered into the default config as well as the docs/man pages (these also would need a slight wording change).

Of course there would still be transition for existing setups that upgrade (which should be kept as is I guess), but since this mostly changes the defaults in the config file and not that much in code/behavior that should be fine.

Maybe it also is a pure downstream decision (patching the docs and the default config), but before suggesting/doing anything like that I wanted to open an upstream discussion about it to see which different opinions exist for that topic.

**Comment by WayneD** [comment]
Didn't older Unix systems have both a nobody user and an nfsnobody user? I know CentOS/RHEL have that.  Looks like Ubuntu decided to go with per-package "nobody" users, so their rsync packages should create an rsyncd user and make that the default user for the daemon. I've just added a configure option `--with-nobody-user=FOO` to go along with the existing option `--with-nobody-group=FOO` to make this easier.
