### ISSUE TITLE
Move on with merging old --detect-renamed patches

### ISSUE THREAD

**Issue by claell** [WayneD/rsync#138]
There is a rather old bug report on bugzilla concerning the detection of moved / renamed files: https://bugzilla.samba.org/show_bug.cgi?id=2294.

There are also patches that implement this functionality. However, those have not been merged, yet. This issue is for tracking the progress of merging them (hopefully soon).

**Comment by WayneD** [comment]
The bugs themselves are good enough.  There are no current plans to merge this at this time.

**Comment by claell** [comment]
This issue was basically thought to come forward with merging them. But we can also continue that in the original bugs, if you prefer.

Can you give some reasoning why there are no plans to merge them in the near future? Maybe lacking time to properly review them? Or not tested thoroughly enough?

I mean those are lying around for a long time now and I'd really like to make use of them without having to apply them myself. There is even at least one downstream issue (for Ubuntu) that is about this functionality and there they argue that patching the software downstream is not very sensible (to which I agree).
