### ISSUE TITLE
Force new features on ?

### ISSUE THREAD

**Issue by benrubson** [WayneD/rsync#14]
Hi,

What about forcing the new features on ?
I think about `xxhash`, `SIMD`, `openssl`...
So that someone compiling / packaging _rsync_ would have to explicitly disable these features if they are not compatible with his system.
I think about this because _rsync_ will flawlessly compile even if the required components for these new features are not found. At this moment the developer will feel happy, but the end-user will miss serious features.

Enforcing them would make these new features more easily / rapidly available in the various systems / distros IMO.

Thank you 👍

**Comment by WayneD** [comment]
Yeah, I was contemplating that myself. I decided to make configure error out if the newest libs or g++ aren't found, but exit with a message that mentions what --disable-FOO option to use if they want to ignore that feature.

**Comment by benrubson** [comment]
Works perfectly fine 👍
Perhaps you forgot the `openssl` case ?
