### ISSUE TITLE
Add: rsync preserves the access time (atime)

### ISSUE THREAD

**Issue by Bd954wxadssa** [WayneD/rsync#140]
Hello,

I am using rsync (3.2.3) and have not found a command that preserves the access time (`atime`) on the destination as a copy of the source. My files and folders are local on the internal disks and want to copy to my external disks. 

Currently only modified time (mtime) is supported.
`rsync -t`

**Comment by WayneD** [comment]
See --atimes, which depends on your OS support for its ability to function. FYI, questions are best asked in the discussions area or on the mailing list, not by creating bugs.
