### ISSUE TITLE
Interaction between rsync, -axX, and 5.10 kernel triggers error from mount point

### ISSUE THREAD

**Issue by psfales** [WayneD/rsync#142]
I'm seeing errors when attempting to use rysnc with -axX when there is a mounted directory somewhere in the tree.    This only started showing up on Fedora 32 and 33 after the recent update from kernel 5.9.x to kernel 5.10.x.    I'm not actually sure if the bug is with rsync or with the kernel.  But, if it's not rsync, I'm hoping the rsync developers can help figure out what the new kernel is doing wrong. 

To reproduce:

```
# Create a test directory containing another subdirectory
mkdir -p testdir/mountpoint

# Rsync that directory to another location with -axX  -> No error
rsync -xaX testdir/ /tmp/testdir/

# mount something on the subdirectory
sudo mount -o loop something.iso testdir/mountpoint

# Rsync that directory to another location with -axX ->  On kernel 5.9.x no error, on 5.10.x, get error
rsync -axX testdir/ /tmp/testdir/
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
```

On kernel 5.10.8, running under strace has this line:

406772 lgetxattr("./mountpoint", "security.selinux", NULL, 0) = -1 EOPNOTSUPP (Operation not supported)

On kernel 5.9.x, there is no error and strace does not show any calls to lgetxattr()

**Comment by WayneD** [comment]
You should take over your xattr name filtering using `--filter '-x foo'` and `--filter '+x bar'` rules. For instance, you might want to include all "user.*" xattr names and exclude everything else. Rsync no longer tries to keep track of what name prefixes are protected by some new kernel or mount, so a modern rsync (at least 3.2.0, but 3.2.3 is even better) lets you control what to do.
