### ISSUE TITLE
patch to access.c

### ISSUE THREAD

**Issue by hdatma** [WayneD/rsync#146]
```
--- ./access.c.orig     Sat Aug  8 12:11:46 2020
+++ ./access.c  Sat Aug  8 12:12:07 2020
@@ -20,6 +20,7 @@
 
 #include "rsync.h"
 #include "ifuncs.h"
+#include "netgroup.h"
 
 static int allow_forward_dns;
```

**Comment by WayneD** [comment]
You don't mention what that's intended to fix, so in the future it would be helpful to provide more info such as:

> NetBSD doesn't declare innetgr() in netdb.h, so it requires an include of <netgroup.h> in order for access.c to compile without the following error|warning ...

I've committed a tweak to configure & access.c that should fix things (be sure to `make reconfigure` or re-run your configure command).

**Comment by hdatma** [comment]
Side note.

```
configure.ac:18: error: possibly undefined macro: AC_HEADER_MAJOR_FIXED
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:766: error: possibly undefined macro: AC_HAVE_TYPE
```

```
>autoconf --version | head -1
autoconf (GNU Autoconf) 2.69
```

**Comment by hdatma** [comment]
I rebased locally, and your patch fails.

**Comment by hdatma** [comment]
Sorry, I confused it. This patch works. The problem is with https://github.com/WayneD/rsync/issues/144.

**Comment by hdatma** [comment]
Ref. https://github.com/WayneD/rsync/issues/148
