### ISSUE TITLE
Suggestion: provide "exclude from transfer start" and "exclude from absolute path"

### ISSUE THREAD

**Issue by DarkTrick** [WayneD/rsync#147]
Note: `man` says `/ specifies that the include/exclude rule should be matched against the absolute pathname`, which is not the case. However, reading SO it seems like this is intended.

Current situation
=============
`--exclude` works for excluding 
- a pattern applied to each single directory
- an absolute path starting from `pwd`

Problem
=======
I think the behavior for "absolute paths" is very confusing. Also it introduces the need to `cd` into the directory to rsync, which leads to very unstable bash scripts.

Suggestion
=========
Provide an option to exclude directories 
1. from an absolute path starting at the file system root (`/`)
2. from a relative path starting at the directory that is copied. 
    Example: 
    `user@user: /$  rsync "~/" "/backupdir" --exclude="foo1"` would backup home dir, but not `~/foo1`

Note: In case this is already possible through some option-trickery, it's not clear from `man`. In that case some sugar and doc update would be nice.

**Comment by WayneD** [comment]
You've misread the manpage. The '/' modifier to a filter rule makes it match against an absolute path.  e.g. `-f'-/ /some/path/here`.

**Comment by DarkTrick** [comment]
Thank you for the reply. 
As stated in the report I feel this possibility is not clear from the docs. As you're not mentioning the docs nor  syntactic sugar, I guess I don't need to hope for either in close future.
...That being said: Thank you for your work on rsync (y)

**Comment by WayneD** [comment]
The man page has a large quantity of information on this subject. See: https://github.com/WayneD/rsync/blob/master/rsync.1.md#filter-rules

Read it from the top down and you'll see that a leading slash in the path means that the name is anchored to match at the top of the transfer, while a '/' modifier is required to turn a rule into one that matches against the whole path.

**Comment by DarkTrick** [comment]
> The man page has a large quantity of information on this subject

Which is one point I'm referring to. 
What do you think about a /use case-driven explanation/ ?

```
Filter Rules
=========
[...]

INCLUDE/EXCLUDE PATTERN RULES
----------------------------------------------------
[...]
- Absolute path filter: [...]
- Relative path filter: if the pattern starts with a / then  [...]
- Filter only directories: if the pattern ends with a / [...]
- Use wildcard filtering: rsync chooses between doing a [...]
  - a '*' matches any path component, but it stops at slashes.
  - use '**' to match anything, including slashes.
  - a '?' matches any character except a slash (/).
  - a '[' introduces a character class, such as [a-z] or [[:alpha:]].
  - Escape wildcard character: in a wildcard pattern, a backslash [...]
  - [...]

```

Then, hopefully, people see information regarding their use case more quickly (without reading everything from top to bottom).
