### ISSUE TITLE
Please add reflink support to 3.2.0

### ISSUE THREAD

**Issue by Polynomial-C** [WayneD/rsync#15]
Hi Wayne,

please add reflink support to 3.2.0 before it gets released. I'm waiting for this feature for a very long time already. 
See https://bugzilla.samba.org/show_bug.cgi?id=10170

**Comment by WayneD** [comment]
No, that's not going to make it. I started on a --clone-dest patch in the rsync-patches git that uses reflinks instead of hard links for efficient backups, but I don't have any way to test it yet.

**Comment by Polynomial-C** [comment]
Fair enough but please make it into a future release. I am really looking forward having this feature in rsync.
