### ISSUE TITLE
Nanosecond is not supported in rsync for access time (atime)

### ISSUE THREAD

**Issue by vanessa794h** [WayneD/rsync#158]
Hey rsync developers, 

I found this bug report and according to the reporter rsync does not preserve the nanoseconds for access time.

https://bugzilla.redhat.com/show_bug.cgi?id=1926517

In addition, it should be checked whether the same problem also occurs with creation time. 

--crtimes, -N

**Comment by WayneD** [comment]
That is correct.  Rsync considers integers adequate for atime & crtime.

**Comment by opty77** [comment]
Any chance that rsync changes its attitude and adds support for nanoseconds? If it works for modification time then why not for all...
