### ISSUE TITLE
Should "rsync -X" take note of the settings in /etc/xattr.conf?

### ISSUE THREAD

**Issue by dhowells** [WayneD/rsync#163]
/etc/xattr.conf can be configured (on some Linuxes, at least), to cause certain xattrs to be skipped in copies.  Note that "cp --preserve=xattr" makes use of this (at least on Fedora - doesn't seem to on Ubuntu).  Should rsync be taking note of this too?

The effect of this can be seen with rsync-3.1.3-11.fc32.x86_64 copying from an file mounted with kafs:

    http://lists.infradead.org/pipermail/linux-afs/2021-March/003502.html

Assuming you've patched your kernel with the patch:

    http://lists.infradead.org/pipermail/linux-afs/2021-March/003501.html

you will see rsync failing because it's trying to copy informational and meta xattrs that don't really exist.

**Comment by dhowells** [comment]
To test this, you need to install the kafs-client and keyutils packages and do "systemctl start afs.mount". Alternatively, you manually mount somewhere, e.g. mount -t afs "#openafs.org:root.cell" /mnt .  You can then do:

  rsync -X /afs/openafs.org/software/openafs/README.TXT /tmp

or, if mounted manually:

  rsync -X /mnt/software/openafs/README.TXT /tmp

**Comment by WayneD** [comment]
Rsync support xattr excludes, which you can use to take full control over what attributes are copied.
