### ISSUE TITLE
persistent failures on MacOS: rsync error: error in rsync protocol data stream (code 12) at token.c(476) [sender=3.2.3]

### ISSUE THREAD

**Issue by yurivict** [WayneD/rsync#168]
I run the command like this on MacOS to the target OS FreeBSD 12.2:
> rsync -avzh yuri@{myhost}.{ext}:qBT_dir/"XX.XXXxxxxXXXxxxxx.[xxx]" .

The directory to be transferred is qbittorrent's 100GB directory with many files about 4GB each.

The first time rsync ran - some files were yet incomplete on the server and it probably downloaded some trash data into them.

When rsync is rerun it fails like this:
```
receiving file list ... done
XX.XXXxxxxXXXxxxxx.[xxx]/
deflate on token returned 0 (2917 bytes left)
rsync error: error in rsync protocol data stream (code 12) at token.c(476) [sender=3.2.3]
rsync: connection unexpectedly closed (3673 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (3667 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/io.c(453) [generator=2.6.9]
```

It doesn't fail every time, it downloads something and then fails.

It could also be that download of unfinished files has nothing to do with these failures.

It looks like a MacOS client side failure.

FreeBSD has rsync-3.2.3

**Comment by yurivict** [comment]
It looks like it usually fails at the end of a large file. When rerun - it fails to verify the file and keeps failing until the unfinished file is removed on the client. Then it continues the download, and sometimes fails again the same way.

It doesn't look like rsync is usable on MacOS.

**Comment by yurivict** [comment]
MacOS has rsync-2,6,9.

**Comment by yurivict** [comment]
I installed in with ```brew install rsync```. ```brew upgrade rsync``` says that rsync-3.2.3 is already installed. Yet, ```rsync --version``` still says that it is 2.6.9.

**Comment by WayneD** [comment]
Stop using the -z option with 2.6.9 and you'll be fine.  As for the newer rsync, you'll probably need to specify its full path, as I'd imagine that one version is in /usr/bin and another is in /usr/local/bin.
