### ISSUE TITLE
--address option not binding correctly?

### ISSUE THREAD

**Issue by rapier1** [WayneD/rsync#169]
I'm trying to use --address to bind the outbound rsync to a specific interface (eg rsync -a --address=192.168.1.105) on a dual homed system. However, all of the traffic is still taking the default interface. Both interfaces are on the same subnet. Both can access the target host via ssh without a problem. Does --address only work between an rsync client and an rsync daemon?

**Comment by WayneD** [comment]
The code calls bind() on the outgoing socket when that option is used.
