### ISSUE TITLE
Website needs updates

### ISSUE THREAD

**Issue by Neustradamus** [WayneD/rsync#17]
There are no links to this GitHub on https://rsync.samba.org/ + https://rsync.samba.org/documentation.html + https://rsync.samba.org/issues.html + https://rsync.samba.org/FAQ.html

There is a bad link: https://rsync.samba.org/bugzilla.html, now it is here.

Only a little section "The latest version via GitHub" in https://rsync.samba.org/download.html

**Comment by WayneD** [comment]
Yup, that was the plan when testing out GitHub: leave most things alone and just mention the new area enough to alert people to its presence.  Now that I've seen what an improvement it is, I've decided to go ahead and start modifying more and more of the website info to mention GitHub as the primary source for rsync (with the samba repo as an auxiliary location).  I've also gone ahead and brought over the rsync-patches repo from samba to GitHub.

One of the best things about the old samba location was the build farm that used to build rsync on solaris, bsd, hpux, etc, etc.  Sadly, that is now defunct. Fortunately I managed to get access to the gcc build farm in time to aid in my release testing, which did help me to find several portability issues.  It's nice to have GitHub actions building the source here on Ubuntu, but I do wish that they had at least some BSD containers as well.

In any case, the web site should be a bit more shiny & new now, at least on the main pages.

**Comment by Neustradamus** [comment]
@WayneD: Thanks for your reply but the website has not been updated.

The new version is here but website is always old.

**Comment by WayneD** [comment]
I've no idea what you're looking at.

**Comment by Neustradamus** [comment]
@WayneD: Nothing about GitHub here:
- https://rsync.samba.org/
- https://rsync.samba.org/documentation.html
- https://rsync.samba.org/issues.html
- https://rsync.samba.org/FAQ.html
