### ISSUE TITLE
rsync Android / TWRP

### ISSUE THREAD

**Issue by 007fred50** [WayneD/rsync#172]
I'm trying to create rsync to my andorid / TWRP So i can backup android folder

My code for compile:
```
./configure --host=arm-linux-gnueabi CFLAGS="-static" --disable-xxhash --disable-zstd
make
make prefix=/home/fredy/Desktop/rsync install
```

i copy the file ("rsync", "rsync-ssl") into /sbin

But i got this error here and testet with command "rsync":
`/sbin/rsync: line 1: syntax error: unexpected "("`

Can you help me out?

Thanks for your time

**Comment by WayneD** [comment]
Looks like you put a bogus script in place of the rsync executable somehow.
