### ISSUE TITLE
Hanging rsync because of ssh issue with D-Bus

### ISSUE THREAD

**Issue by realsimix** [WayneD/rsync#176]
There is currently a problem with rsync when running it on RHEL8 with ssh. The problem is that ssh can hang because of a problem with D-Bus:

https://bugzilla.redhat.com/show_bug.cgi?id=1940067

Of course the problem is not really in rsync but I thought why not trying to make rsync over ssh a bit more robust?

Maybe one of the following could help:
a) add `-x` as default arg if `RSYNC_RSH="ssh"`, this would stop ssh from trying to forward X11.
b) just `unsetenv("DISPLAY");` before ssh is launched, this should also stop ssh from trying to forward X11.

Thanks,
Simon

**Comment by WayneD** [comment]
I've added some code to unset the DISPLAY var in the environment.  Thanks!

**Comment by realsimix** [comment]
Thanks for looking into it!
