### ISSUE TITLE
Feature wish: transient server mode

### ISSUE THREAD

**Issue by Cigaes** [WayneD/rsync#180]
Hi. I would like to be able to do something like that:

```
alice@10.0.0.1 $ rsync -v --transient 1234
```

```
bob@10.0.0.2 $ rsync -va --transient dir/ 10.0.0.1:
```

It would do the same as:

```
bob@10.0.0.2 $ rsync -va dir/ alice@10.0.0.1:
```

except that it does not require alice to type their SSH credentials on bob's computer, or even to run a SSH server at all.

I have tried fiddling with `socat`/`nc` to run the server and the `-e` option to connect to it, but it does not seem conveniently done.

Thanks in advance.

**Comment by WayneD** [comment]
The 10.0.0.1 computer can run a daemon, and a non-root user can choose to use a non-protected port:

`rsync --daemon --no-detach --port=8873 --config=foo.conf`

You just need to create a simple foo.conf file that defines a module with a path.
