### ISSUE TITLE
Feature request: checksum-choice=none default for local transfers

### ISSUE THREAD

**Issue by rafiyr** [WayneD/rsync#182]
I would like checksum choice default to none for local transfers (like --whole-file).

The one caveat is that if anything else would normally use the checksums, it should stick to the current behavior.  That includes the --checksum flag, logging where the checksums are in the format, and I'm not sure what else.

**Comment by WayneD** [comment]
Sorry. It'll never be the default, but the option is there for you to use as you see fit.
