### ISSUE TITLE
Bug in man page: comment syntax in `exlude-from` / `include-from` files

### ISSUE THREAD

**Issue by ThomasLandauer** [WayneD/rsync#188]
`man rsync` tells me at `--exclude-from=FILE`:
> Blank lines in the file and lines starting with ’;’ or ’#’ are ignored.

However, when I put this line in an `exlude-from`:
```
foo # bar
```
... I'm getting the file `foo` copied too. So it looks like that in fact the line doesn't have to *start*  with `#`, but rather just *contain* `#` somewhere.

* rsync  version 3.1.3  protocol version 31

**Comment by WayneD** [comment]
That excludes a file named `foo # bar` so it's not surprising that a file named foo gets copied (since it wasn't excluded).

**Comment by ThomasLandauer** [comment]
@WayneD OK, thanks, I see :-)
What about adding this example to the man page? Not being able to add an *inline* comment is somewhat uncommon and might confuse others too...

**Comment by WayneD** [comment]
I attempted to make the whole-line natures of the comments clearer in the manpage.
