### ISSUE TITLE
SIMD check in configure.ac is too strict

### ISSUE THREAD

**Issue by Polynomial-C** [WayneD/rsync#19]
The line
```
if test x"$CXX" = x"g++"; then
```
is too strict for a check for g++. In Gentoo Linux we have `x86_64-pc-linux-gnu-g++` (or similar string for other arches) in our `CXX` variable and thus the check fails even if the CPU supports SIMD.

**Comment by Polynomial-C** [comment]
How about this?
```
--- rsync-3.2.0pre3/configure.ac
+++ rsync-3.2.0pre3/configure.ac
@@ -202,7 +202,7 @@
 if test x"$enable_simd" = x"yes"; then
     # For x86-64 SIMD, g++ is also required
     if test x"$build_cpu" = x"x86_64"; then
-       if test x"$CXX" = x"g++"; then
+       if echo "$CXX" | grep -q 'g++$'; then
            # AC_MSG_RESULT() called below
            SIMD="$SIMD x86_64"
        else
```

**Comment by WayneD** [comment]
I turned it into a case statement.

**Comment by Chainfire** [comment]
Note that my pull request for build issues with the SIMD build change this again, I suspect it will work (in the old case it also didn't work if $CXX contained the full path to g++) as submitted, but it couldn't hurt to test it specifically.
