### ISSUE TITLE
Support of `--crtimes`, `-N` in Windows

### ISSUE THREAD

**Issue by AlttiRi** [WayneD/rsync#194]
I have created the related issue already there: https://github.com/msys2/MINGW-packages/issues/8951
But maybe it makes sense to do it also here. So:

Currently `rsync` works fine in Windows with Git-Bash [(How to install)](https://gist.github.com/hisplan/ee54e48f17b92c6609ac16f83073dde6#gistcomment-3605244)

But it does not support `--crtimes`,`-N` — "preserve create times" flag.

I use `Robocopy.exe` now, it keeps file creating date by default, but it does not have any flag to verify checksum (`-c`, `--checksum`) while `rsync` does not support keeping of file creating time since this feature is not implemented:
```
rsync: This rsync does not support --crtimes (-N)
rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
```

With this feature `rsync` would be preferable that `Robocopy.exe`.

**Comment by WayneD** [comment]
While cygwin provides an st_birthtim value in the stat struct, it doesn't provide a means of setting the birth time, so this is not currently possible.

**Comment by AlttiRi** [comment]
If it's not possible to do even in 2021 I don't think that it will changes in future.
So, maybe use Win API to do this?
For example: https://github.com/baileyherbert/utimes/blob/master/src/addon/binding.cc

I assume the same thing is with iOS.

**Comment by WayneD** [comment]
Thanks for pointing out that sample code.  I committed a working version of the feature on cygwin.  See what you think.

**Comment by AlttiRi** [comment]
I almost have no  C/C++ experience, so probably I can test it only when it will be released on [repo.msys2.org](https://repo.msys2.org/msys/x86_64/)

But it looks that they rarely do rebuilding, the last one was in 2020

![image](https://user-images.githubusercontent.com/16310547/125075719-ab2e8b00-e0c7-11eb-971f-a444f1d0d1e5.png)

**Comment by WayneD** [comment]
The nightly github actions does a cygwin build. For instance: https://github.com/WayneD/rsync/actions/runs/1014572098

Look for the artifact zip files near the bottom and snag the cygwin one.  It does require various libraries to be installed, but if you have a recent rsync from cygwin, that should have installed them for you.

**Comment by AlttiRi** [comment]
I have rsync compiled with MinGW, not with Cygwin.
It looks that I need manually look for: `cygwin1.dll`, `cyglz4-1.dll`, `cygzstd-1.dll`, `cygcrypto-1.1.dll`.

**Comment by AlttiRi** [comment]
I have install the required modules and now:
```
0 [main] rsync (6164) C:\Downloads\cygwin-bin\rsync.exe: *** fatal error - cygheap base mismatch detected - 0x180347408/0x180357408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

> `x:\cygwin\bin`

Is it requires exactly 32-bits Cygwin? Since my is in `C:\cygwin64\bin`.

**Comment by AlttiRi** [comment]
`--crtimes` looks working.

**Comment by AlttiRi** [comment]
I did not tested this case, so I just ask: does it keep in mind the case of setting the creating time attribute to sym link exactly?
https://github.com/baileyherbert/utimes/issues/8

**Comment by AlttiRi** [comment]
Also I have noted the problem with file permissions, but I don't sure is it reason of Cygwin's build, or it's because I do it in a virtual machine. 
Need to test it later. 

![Screenshot](https://user-images.githubusercontent.com/16310547/125143402-43a62900-e123-11eb-96d0-e4011b8590ab.png)
![Screenshot_1 - edited](https://user-images.githubusercontent.com/16310547/125143589-c5965200-e123-11eb-8912-4daddd4f023c.png)



In main OS rsync (from Git Bash) has no such problem.

**Comment by RichardFevrier** [comment]
Is the solution proposed by @AlttiRi is currently included in the `master` branch @WayneD?
