### ISSUE TITLE
Transfer of a file is not stopped/skipped when temporary file creation failed

### ISSUE THREAD

**Issue by tomty89** [WayneD/rsync#197]
Is it a known flaw/bug that even when the temporary file creation failed, rsync will go on transferring a file till the end? (and write to...nowhere?) Is there anyway to workaround it?

I am NOT talking about making transfer of *files* to stop when *one* file cannot actually be transfered btw.

**Comment by WayneD** [comment]
Yes, this is due to the piped nature of the 3 independent processes.
