### ISSUE TITLE
rrsync with --mkpath flag

### ISSUE THREAD

**Issue by col-panic** [WayneD/rsync#200]
Using  `rsync  version 3.2.3  protocol version 31` with the accompanied `/usr/bin/rrsync` via an ssh connection with the `--mkpath` flag returns

`/usr/bin/rrsync: invalid rsync-command syntax or options`

using without `--mkpath` works as expected.

**Comment by WayneD** [comment]
I've updated the options in the [very latest rrsync](https://github.com/WayneD/rsync/blob/master/support/rrsync). Thanks!

**Comment by col-panic** [comment]
Greate - thanks a lot!
