### ISSUE TITLE
Apple m1 crashes with rsync 3.2.3 (via brew)

### ISSUE THREAD

**Issue by phenomeus** [WayneD/rsync#205]
i have the same crashes as this user here: https://apple.stackexchange.com/questions/421007/rsync-3-2-3-keeps-crashing-on-mac-mini-m1

my machine is a m1 MacBook Air with 8GB ram, Big Sur 11.5.1 (20G80) and installed rsync 3.2.3 with homebrew

right now I reverted back to apples original rsync 2.6.9. and try to produce the same crash by cloning two large photolibraries, around 1.5 TB

**Comment by WayneD** [comment]
Someone will need to dig in and debug things. I don't use any Apple systems to be able to test.

**Comment by jonglezb** [comment]
A kernel panic is an OS issue, not an application issue. OS X had some early stability issues on M1, recent OS X updates should work better.
