### ISSUE TITLE
adding a keyopt for openssl to rsync-ssl

### ISSUE THREAD

**Issue by fabolhak** [WayneD/rsync#211]
Hello, 
thank you for the very nice script `rsync-ssl`. It really helped a lot including TLS encryption in our use case. We only had to add an keyopt variable to the script, because in our use case the certificate and key are stored in two separate files. I was wondering if it is intentional to have only one certificate file provided to openssl via the `-cert` option and no key file? Maybe there is some file format which includes both which I'm not aware of? If not you would be glad to provide a pull request to add a keyopt for the openssl method:

```
79a80,85
>     if [[ -z "$RSYNC_SSL_KEY" ]]; then
>       keyopt=""
>     else
>       keyopt="-key$optsep$RSYNC_SSL_KEY"
>     fi
>
132c138
<       exec $RSYNC_SSL_OPENSSL s_client $caopt $certopt -quiet -verify_quiet -servername $hostname -connect $hostname:$port
---
>       exec $RSYNC_SSL_OPENSSL s_client $caopt $certopt $keyopt -quiet -verify_quiet -servername $hostname -connect $hostname:$port
```

Just wanted to ask before creating the PR :)

**Comment by WayneD** [comment]
That seems fine to me.  Please include a change to rsync-ssl.1.md (ENVIRONMENT VARIALBLES) in your pull request.
