### ISSUE TITLE
Rsync greeting message format

### ISSUE THREAD

**Issue by gozeloglu** [WayneD/rsync#215]
Hi,

I am trying to understand the response message format when we connect to server successfully. Simply when I connect to Rsync server (Docker container in my case), I am getting a response `@RSYNCD: 31.0`. But, I am not sure official format of this message. When I read the https://download.samba.org/pub/rsync/rsync.html document, it says that "the remote daemon may print a message of the day when you connect.". So, I understand that, this message can be changed by server admin. When I look at the code, I see the following line https://github.com/WayneD/rsync/blob/a6bdf313f239cabfef445bc3658b79aec8a40c37/clientserver.c#L180 

I did not understand the code very well, but by intuition, `@RSYNCD:` should be at the beginnig of the line and rest of the line can be configured. Can you verify this situation? If I am wrong, is there any specific greeting message format? 

![image](https://user-images.githubusercontent.com/33967642/130792925-edc5e53e-0603-44f7-abf6-08c50964b6fc.png)

Here is my output when I connect with Telnet.

**Comment by gozeloglu** [comment]
I have just found something here: https://github.com/WayneD/rsync/blob/05540220a92dd06b62f240f6178921dde5697dd3/csprotocol.txt#L12 
I think, this one answers my question. If yes, please notify me.

**Comment by WayneD** [comment]
Right. The version (first number) is the max protocol version the daemon supports.  The subprotocol version is usually 0 except for test versions working on a follow-up protocol version.  For a client that doesn't support test versions, you'd just decrement the main version if the subprotocol version is non-zero (i.e. advertising 32.2 means that version 31 is the largest official protocol that it supports).
