### ISSUE TITLE
rsync copy file when birth

### ISSUE THREAD

**Issue by soloturn** [WayneD/rsync#221]
i renamed a file with same modification timestamp. rsync does not copy it, despite "birth" and "size" are different.  i am using "rsync -arvu". this sounds not so intuitive - but rsync is so proven that i am hesitating to call this a bug, maybe i miss something?

```
> stat '/loc1/f' 
Size: 1362996731	Blocks: 2662112    IO Block: 4096   regular file
Modify: 2021-01-16 12:13:19.171000000 +0100
Change: 2021-09-11 23:30:56.396333647 +0200
Birth: 2021-08-05 00:04:18.574123516 +0200
```
```
> stat '/loc2/f' 
Size: 2083437363	Blocks: 4069224    IO Block: 4096   regular file
Modify: 2021-01-16 12:13:19.171126769 +0100
Change: 2021-01-17 08:52:11.762480315 +0100
Birth: 2021-01-17 08:51:40.562721004 +0100
```

**Comment by WayneD** [comment]
Don't use -u for normal copies.  That a special kluge to try to protect files on the receiving side based on mtime.
