### ISSUE TITLE
Man page should say if speedup means "X times faster" or "X percent faster"

### ISSUE THREAD

**Issue by jidanni** [WayneD/rsync#228]
```
sent ... received ...bytes  ... bytes/sec
total size is ...  speedup is 10.70
```

The rsync man page should say if 'speedup' means "X times faster" or "X
percent faster" or what.

In fact, if like #229 the units of speedup were included in the message,
then the manpage needn't bother.

**Comment by WayneD** [comment]
I'm adding a description of what the speedup means to the man page.
