### ISSUE TITLE
Always mention units

### ISSUE THREAD

**Issue by jidanni** [WayneD/rsync#229]
Here we see rsync is very careful to mention what units it is talking about,
```
sent 79 bytes  received 12 bytes  9.58 bytes/sec
total size is 92,157  speedup is 1,012.71
```
Alas, except on the second line, where it has suddenly forgot to mention what units of size, and... #228.

**Comment by WayneD** [comment]
Yeah, the second line assumes that you know that sizes are bytes, while the "speedup" is just feel-good mysticism.  I'm not keen on changing this message at this time, though I am documenting it in the man page.
