### ISSUE TITLE
rsync fails to copy if the source is a read-only folder

### ISSUE THREAD

**Issue by Cyberavater** [WayneD/rsync#232]
Throws `Read-only file system (30) Skipping any contents from this failed directory` if the source is read-only.

I've asked/explained briefly here: https://askubuntu.com/questions/1366414/how-to-copy-read-only-files-and-folder-using-rsync

P.S. Don't ask me to get write access for the source directory, that's not possible.

**Comment by WayneD** [comment]
Right, if you don't have permission to read it, you can't copy it.

**Comment by Cyberavater** [comment]
It turns out that the version provided by google collab is 3.1.2 (which is buggy), while the latest version is 3.2.3 (which has the issue fixed).

Details: https://askubuntu.com/a/1368500/1094129
