### ISSUE TITLE
rsync failes silently when folder names end with a space

### ISSUE THREAD

**Issue by Hypercookie** [WayneD/rsync#233]
rsync (3.2.3) shows correct verbose output and seems to sync the files without problem (over ssh).
Looking inside the target filesystem shows instead of the (sub-)folder to sync a folder named like "MX1W06~R" is created  containing no files. This makes rsync "sync" the files every time without success.

This bug is easily reproducable by syncing a directory containing a folder which has a space at the end of its name.
Like "folder ". 
Note that i discovered this by acident... im not a maniac.

For reference here is the full command :
`rsync --exclude=".*" -av --progress  source_path name@host:target`

**Comment by WayneD** [comment]
Works fine for me. I tried linux -> linux and linux -> windows.  It might be some kind of an OS issue on your destination host.

**Comment by Hypercookie** [comment]
Im using MacOS -> Linux .
I will test it with another destination host and another source host.
