### ISSUE TITLE
Getting paranoid when seeing weird group name in rsync.

### ISSUE THREAD

**Issue by arafatx** [WayneD/rsync#234]
To demonstrate this, I use the following syntax to upload file to remote server:

`rsync -Pav -e "ssh -q -o 'StrictHostKeyChecking no' -i '${rsa_key}'" /local/file.txt "me@server:~/"`

It works well, but when I look at the file permission and group I got the following result:

`770:-rwxrwx---	root:gotify       file.txt`

I'm confused about the group name that suddenly became `gotify`. Yes, I have gotify installed in my system but how is this possible that rsync use this group name? When I look at the `/etc/group` I don't find any duplicated group name. The user gotify only belongs to one group

If I remove gotify username and gotify group, Then when I use rsync I got `UNKNOWN` group and when I recreate the username and group, rsync will use the same group name for uploaded file in remote server. Can anyone explain this ?

**Comment by WayneD** [comment]
If you want groups to match between hosts then you need all the names to exist on both hosts.  When a group name doesn't exist, it is created by number.

**Comment by arafatx** [comment]
I don't think you understand what I'm trying to tell.. I know how to rename the group name before push the file on rsync and it is not what I want to understand.

But the last part of what you said:

`When a group name doesn't exist, it is created by number.`

Can you explain more specific on the this part ? So, rsync using group ID? But why did it choose group ID that belongs to gotify ?

**Comment by arafatx** [comment]
So, the gotify group is first had GID `918` and after I removed the group and recreate it is now has GID `988`. And now when using rsync to push file, why did the file has group name still belongs to gotify? I really want to understand the last part of what you just said above.

**Comment by arafatx** [comment]
I think you might have misunderstood my question. I really know how to rename the group name before push the file on rsync, there is no issue if I want to have matching permission between local and remote files. The issue here is that, rsync select the same group name whenever the ID of the group has changed.

You said:

`When a group name doesn't exist, it is created by number.`

Can you explain more specific on the this part ? What do you mean by `it is created by number`? Do you mean rsync use GROUP ID? But why did it choose group ID that belongs to gotify ?

You see first, my gotify group is first had its GID `918` and after I removed the group and recreate it is now has GID `988`. And now when using rsync to push file, why did the file has group name still belongs to gotify? I really want to understand the last part of what you just said above and maybe that is the clue

The reason I asked this question is, I think gotify has been compromised and someone might have modified rsync to have file group belong to gotify. So, if they gained access into gotify web application, they can access the server and all file pushed via rsync that have group belong to gotify will be able to read by gotify users. I might be wrong in this part but still it makes me feel paranoid. So my question is more on security issue here.

**Comment by arafatx** [comment]
I actually can prevent this from happening by calling rsync with -og --chown=root:root (so it would always use root group by default). But I just want to understand the technical part how and why did rsync without the above option use gotify group name when uploading. Is there a config somewhere that it stores to memorize this group name?

**Comment by WayneD** [comment]
It just looks up groups by name: if not found, it falls back to using the gid.  People doing backups tend to specify `--numeric-ids` so that the save/restore is always accurate no matter what names are used (you just can't expect the names to be right on the backup host in that situation, just the ids).  When using group names, if you make sure that all the in-play group names get created on all the hosts in a transfer, it can always handle the local & remote name <=> id translations.

I'll also mention that more complex conversion idioms are possible, such as the rsync daemon "name convert" setting (see support/nameconvert for an example helper script) or explicit name mapping using scripts like the support/mapfrom & support/mapto.  These can be used to force particular id values for particular names.

**Comment by arafatx** [comment]
Thanks for replying @WayneD . I think I understand now.
