### ISSUE TITLE
rsync --info=CMDLINE or CMD

### ISSUE THREAD

**Issue by reikred** [WayneD/rsync#237]
When logging an rsync run to a logfile it would be useful if the logfile could start with a full replica of the commandline.

I poked around a bit in the manual and settled on --info=CMD (nice and short) would be a nice way to ask for the cmdline to be replicated in the output.

That might be a pretty easy option to add for someone who knows their way around the rsync source code?

**Comment by reikred** [comment]
Note to self: options.c is where options and their values are defined

search info repo:WayneD/rsync

**Comment by WayneD** [comment]
I'd suggest a shell wrapper script for this purpose:
```shell
#!/bin/sh
REAL_RSYNC=/usr/bin/rsync
do_echo=yes
# If someone installs this as "rsync", make sure we don't affect a server run.
for arg in "${@}"; do
    if [ "$arg" = --server ]; then
        do_echo=no
        break
    fi
done
[ $do_echo = yes ] && echo "CMD: rsync $*"
exec $REAL_RSYNC "${@}"
```
