### ISSUE TITLE
rsync hangs from fsfreeze source

### ISSUE THREAD

**Issue by laurivosandi** [WayneD/rsync#240]
Hi, I am probably trying something too esoteric and it's not supported, but I'd like to understand why.

Basically I run Mongo, Samba, MariaDB and bunch of other read-write workloads on a node that I am attempting to backup while it's running. This is sort of attempt to implement application neutral backup strategy.

I used `fsfreeze` to freeze writes to the source directory. But oddly enough `rsync` hangs while reading from such source and the files where it gets stuck look like lockfiles.

**Comment by WayneD** [comment]
I imagine that you need to mount the source dir with noatime flag or try using the `--open-noatime` option.

**Comment by laurivosandi** [comment]
Thanks for excellent suggestion, but this did not help. In fact I originally already used the `--noatime` flag.

Note that this seems to happen on XFS. On another machine ext4 doesn't seem to suffer this issue.

**Comment by WayneD** [comment]
In any case, this is some kind of file system issue, not an rsync issue.
