### ISSUE TITLE
`rsync --chown` doesn't work without `--owner` and/or `--group`

### ISSUE THREAD

**Issue by aagor** [WayneD/rsync#242]
Hello,
during my latest backup, i found a weird behaviour of rsync.
It's not respecting the `--chown`-option in some cases.
Take a look at the following example:
```bash
mkdir /tmp/rsync-chown-bug
cd /tmp/rsync-chown-bug
mkdir src
touch src/file
sudo rsync -r --chown=user:user                 src/ dest-without-owner-group/
sudo rsync -r --chown=user:user --owner --group src/ dest-with-owner-group/
find -ls
```
```
130      0 drwxr-xr-x   5 user     user          100 Okt 18 18:38 .
135      0 drwxr-xr-x   2 user     user           60 Okt 18 18:38 ./dest-with-owner-group
136      0 -rw-r--r--   1 user     user            0 Okt 18 18:38 ./dest-with-owner-group/file
133      0 drwxr-xr-x   2 root     root           60 Okt 18 18:38 ./dest-without-owner-group
134      0 -rw-r--r--   1 root     root            0 Okt 18 18:38 ./dest-without-owner-group/file
131      0 drwxr-xr-x   2 user     user           60 Okt 18 18:38 ./src
132      0 -rw-r--r--   1 user     user            0 Okt 18 18:38 ./src/file
```
As you can see, rsync doesn't use the specified user/group for new files unless the options `--owner` and `--group` are used.
For existing files, this is the expected behaviour, but for new files i expect rsync to not ignore the `--chown`-option.

For `--chmod` and `--perms` rsync works as expected: For new files the specified permissions are always used, for existing files only when `--perms` is also present.
The current behaviour of `--chown` is counter-intuitive and not consistent with the `--chmod`/`--perms`-option.

**Comment by WayneD** [comment]
This was fixed in git a little bit ago. Thanks!
