### ISSUE TITLE
Support for remote source && remote destination, with local host as gateway

### ISSUE THREAD

**Issue by ppom0** [WayneD/rsync#243]
Hello!

I have this use case: I want to transfer a +100GB file between two hosts that can't connect to each other.

The `-3` option of `scp` permits to have the local host connect to the two remote hosts and act as a gateway to transfer files.

- I could do `scp -3 src:file dest:`, **but** in case of network error I would have to restart from the beginning.
- I could also do `rsync --append src:file /tmp/file` then `rsync --append /tmp/file dest:file`, **but** it would take twice the time and I would need +100GB spare on the local host to do that.

Would it be manageable to implement `-3` on rsync ?

Thanks!

**Comment by aopom** [comment]
It indeed seems easier to do that than the amount of work needed to add multiple SSH support to rsync. Thanks for answering!
