### ISSUE TITLE
Mute `skipping non-regular file` for `info=skip0` or give an option to mute them outside of `--quiet`

### ISSUE THREAD

**Issue by JhonnyTheJeccer** [WayneD/rsync#248]
I am using rsync with `--info=skip0 --no-links`, but the output is still filled with `skipping non-regular file` messages. 
This seems like a conflict to what `--info=help` reports: 
`Use OPT or OPT1 for level 1 output, OPT2 for level 2, etc.; OPT0 silences.`
and
`SKIP       Mention files that are skipped due to options used`.

Even if this is the desired result, I would still prefer to not have such messages in the output (in the log file its fine), as my `SRC` contains a lot of symbolic links.

-------------------------------------------------------

I found a question on [unix.stackexchange.com](https://unix.stackexchange.com/questions/446440/exclude-symbolic-links-from-rsync-without-excessive-notification) for my exact problem, but the solutions either do not work or are very unpractical for my usecase.

I also found two patches for similar issues, which were probably never applied:
1. [mute all `skip non-regular file` messages with `--info=skip0`](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869280)
2. [only print `skip non-regular file` messages when `verbose > 1`](https://www.mail-archive.com/rsync@lists.samba.org/msg13266.html)

If none of the patches result in desired behaviour, I would like to suggest to add another `--info` option (or another `rsync` option) to silence all `skip non-regular file` messages, which could also resolve or aid #111 .

With either solution, I would also suggest to update the output of `--info=help` accordingly, as currently there is no mention of `skip non-regular file` messages not being muted by `--info=skip0`.

And yes, I am aware of `--quiet`, but I would like to still be able to have output.

-------------------------------------------------------

Full command that is used: 
`sudo rsync -aAXN --fileflags --open-noatime --fake-super --info=skip0,progress2,stats3 --no-links --log-file=FILE --link-dest=DIR SRC DEST 2>&1 | tee FILE` 
I use `2>&1 | tee FILE` because the command is constructed and executed by a python script, but I still want to see the regular output (the issue persists with executing `rsync` manually).

System:
macOS 10.15.7

`rsync` installation:
Installed using `brew`

Output of `rsync --version`: 
```
rsync  version 3.2.3  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, hardlink-specials, symlinks, IPv6, no atimes,
    batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv,
    symtimes, no prealloc, stop-at, crtimes, file-flags
Optimizations:
    SIMD, asm, openssl-crypto
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

**Comment by WayneD** [comment]
This is a bit of a tricky one since SKIP0 is the default. I don't want to turn off the skip messages by default because the messages are notifying a casual user that rsync has the horrible default of skipping symlinks.  However, always mentioning expected skips is indeed annoying.

The `--info=skip` option is currently controlling the skipped transfer messages, not the skipped input types.  I have thought of one possible solution where SKIP1 becomes the new default (allowing SKIP0 to silence these non-regular-file skips) all without sending an `--info=skip1` to the remote rsync (which may be older), but this would mean that script writers that currently use `--info=skip` would need to change to `--info=skip2`, so I'm debating if this is a good idea.

Another alternative I'm considering is to make an explicitly specified `--no-links` option silence the message (and force the normally superfluous option to be sent to a remote receiver).  I'm currently leaning in this direction.

**Comment by JhonnyTheJeccer** [comment]
I agree that the first option is probably not as good of an idea if `--info=skip0` is the default (and a notification for casual users is always nice). Then the second one would also be problematic, as it might interfer with already finished projects (and changing the default of an info option sounds a bit too much in this case).

The last option is probably the best of them, as, like you said, another `--no-links` would not alter the behaviour of `rsync`, but allow better output control. And the messages would still appear when links are not explicitly excluded. Though, including those messages in the log can still be useful.

**Comment by JhonnyTheJeccer** [comment]
I have tested the new feature, but it seems the `nonreg` messages are also completely missing from the `--log-file=FILE` file. According to the manpage, the log in this file should only be modifyable with `--log-file-format=FORMAT`.

**Comment by WayneD** [comment]
Right, the messages are completely skipped when the user is aware of the skipping going on.

**Comment by JhonnyTheJeccer** [comment]
Alright, i thought this might have been a bug
