### ISSUE TITLE
--link-dest with rrsync: incorrect path handling in rrsync

### ISSUE THREAD

**Issue by PopGreene** [WayneD/rsync#255]
INCORRECT BEHAVIOR:

When a specified path is under the restricted directory, the restricted directory is prepended.

DESIRED BEHAVIOR:

Recognize when a path is under (i.e. begins with) the restricted directory and do not prepend the restricted directory.

DETAILS:

On Debian Bullseye, my backup repository on my server looks like:

```
ls -l /vault/bellman
  ...
drwxr-xr-x  63 vault vault 4096 Nov  9 07:38 rob-20211110
drwxr-xr-x  63 vault vault 4096 Nov 10 16:52 rob-20211111
drwxr-xr-x  63 vault vault 4096 Nov 11 11:38 rob-20211112
```

I've placed this in authorized_keys for the relevant key:

`restrict,command="/usr/bin/perl /usr/share/doc/rsync/scripts/rrsync -wo /vault/bellman" ...`

I attempt:

```
rsync --dry-run -av --link-dest=rob-20211112 --exclude=**/.cache --exclude=**/.local/share/Trash /home/rob/ vault_rsync:rob-20211114
sending incremental file list
created directory rob-20211114
--link-dest arg does not exist: /vault/bellman/rob-20211114/rob-20211112
```

This makes sense.  The rsync documentation says that the --link-dest directory, if relative, is relative to the target directory.

Next, I try:

```
rsync --dry-run -av --link-dest=../rob-20211112 --exclude=**/.cache --exclude=**/.local/share/Trash /home/rob/ vault_rsync:rob-20211114
Do not use .. in --link-dest; anchor the path at the root of your restricted dir.
```

Also makes perfect sense.  Allowing ../ could break out of the restricted directory hierarchy.

I think this is all that's left:

```
rsync --dry-run -av --link-dest=/vault/bellman/rob-20211112 --exclude=**/.cache --exclude=**/.local/share/Trash /home/rob/ vault_rsync:rob-20211114
sending incremental file list
created directory rob-20211114
--link-dest arg does not exist: /vault/bellman/vault/bellman/rob-20211112
```

This demonstrates the incorrect behavior.

**Comment by WayneD** [comment]
Specify "/" instead of "/vault/bellman" to refer to the root of the restriction.
