### ISSUE TITLE
Further issue with lib/md5-asm-x86_64.s

### ISSUE THREAD

**Issue by debohman** [WayneD/rsync#26]
About the fix from pull request https://github.com/WayneD/rsync/pull/25#issue-437364767, this seems to not enable dead code removal by the linker on macOS. I propose something like the following in addition, to align with the code inclusion in lib/md.5.c:

```
diff --git a/Makefile.in b/Makefile.in
index 31ddc43b..3dc37420 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -135,7 +135,7 @@ simd-checksum-x86_64.o: simd-checksum-x86_64.cpp
 	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c -o $@ $(srcdir)/simd-checksum-x86_64.cpp
 
 lib/md5-asm-x86_64.o: lib/md5-asm-x86_64.s
-	$(CC) -c -o $@ $(srcdir)/lib/md5-asm-x86_64.s
+	$(CC) -I. -c -o $@ $(srcdir)/lib/md5-asm-x86_64.s
 
 tls$(EXEEXT): $(TLS_OBJ)
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(TLS_OBJ) $(LIBS)
diff --git a/lib/md5-asm-x86_64.s b/lib/md5-asm-x86_64.s
index a3126151..8299f203 100644
--- a/lib/md5-asm-x86_64.s
+++ b/lib/md5-asm-x86_64.s
@@ -24,6 +24,10 @@
  * show any significant difference in performance, though.
  */
 
+#include "config.h"
+
+#ifndef USE_OPENSSL
+
 .text
 .align 16
 
@@ -691,3 +695,5 @@ md5_process_asm:
 	ret
 .L_md5_process_asm_end:
 .size md5_process_asm,.L_md5_process_asm_end-md5_process_asm
+
+#endif
```
Comments?

ETA: I realize that this is not a perfect solution, since the use of md5_process_asm is further predicated on `#if defined(HAVE_SIMD) && (CSUM_CHUNK == 64)`.

**Comment by WayneD** [comment]
Actually, we need to change the asm file from .s to .S in order to get the preprocessor to run on it. Is a .s file preprocessed for you on macOS?  In any case, I have twiddled that and also tweaked things so that it is not created when CSUM_CHUNK != 64 (the file shouldn't even get compiled if HAVE_SIMD isn't defined).

**Comment by debohman** [comment]
The .s is preprocessed for me with clang 10.0.0. This is the public version of clang, not Apple's.

What about the case where you are using both the SIMD code and OpenSSL? Also, what is the case where `CSUM_CHUNK != 64`?

**Comment by WayneD** [comment]
The openssl code is used for MD5 checksums instead of the MD5 asm code, when it is enabled. The chunk size is always 64, but if it were not, then the asm code would not get used.

**Comment by debohman** [comment]
Right. I just realized that those pesky asm directives which were tripping up the Apple assembler were there so that the linux linker could do dead code stripping. The code was there, unused in the rsync I built on macOS.

**Comment by WayneD** [comment]
The ifndef for openssl should strip it all out when it's not needed.

**Comment by debohman** [comment]
Agreed.

**Comment by WayneD** [comment]
I've also decoupled the asm code from the simd code. In my latest commit configure will enable the use of the asm code on x86_64 build targets, with a --disable-asm configure override available. This will allow someone who can't use openssl code (or doesn't want to) to still get the MD5 asm improvements, even if their c++ setup can't handle the simd stuff.

**Comment by debohman** [comment]
Sounds good!
