### ISSUE TITLE
rsync should be able to automatically restart the transfer when the remote shell command dies

### ISSUE THREAD

**Issue by vinc17fr** [WayneD/rsync#263]
It happens that a SSH connection may unexpectedly be closed during a transfer, for various reasons. So rsync should be able to automatically restart the transfer when the remote shell command dies. And an automatic restart should probably be the default when `--partial` is used. If `--partial` is not used, this may not be a good thing as a SSH disconnection could occur again and again on a same big file.

**Comment by WayneD** [comment]
That would indeed be wonderful, but it won't ever happen without a full redesign.
