### ISSUE TITLE
rysnc --update fails

### ISSUE THREAD

**Issue by heavyarms2112** [WayneD/rsync#266]
Have tried to rsync from a nas to local machine which fails as below. The issue is if the file exists in local machine.
`rsync error: error in rsync protocol data stream (code 12) at io.c(228) [receiver=v3.2.3-133-g512acd12]
rsync: [generator] write error: Broken pipe (32)
rsync error: unexplained error (code 255) at io.c(837) [generator=v3.2.3-133-g512acd12]
rsync: connection unexpectedly closed (49886 bytes received so far) [generator]`

command used
```rsync --update --archive --recursive --verbose --partial --progress --no-whole-file --sparse --inplace --files-from=source_file```

**Comment by WayneD** [comment]
All that says is that the remote side closed the connection for some reason. The https://rsync.samba.org/issues.html page has some suggestions for how to look into the issue, including a debug-rsync shell script that might help you figure out what is failing.

**Comment by heavyarms2112** [comment]
@WayneD  thanks for commenting. The debug script spit out the below as last few lines.

`70791 20:06:34 mprotect(0x7f31cbb37000, 180224, PROT_READ) = 0
70791 20:06:34 mprotect(0x7f31cbb71000, 4096, PROT_READ) = 0
70791 20:06:34 mprotect(0x7f31cbc1a000, 4096, PROT_READ) = 0
70791 20:06:34 mprotect(0x7f31cbc3b000, 4096, PROT_READ) = 0
70791 20:06:34 mprotect(0x7f31cbc46000, 4096, PROT_READ) = 0
70791 20:06:34 mprotect(0x561685fb1000, 8192, PROT_READ) = 0
70791 20:06:34 mprotect(0x7f31cbc89000, 4096, PROT_READ) = 0
70791 20:06:34 munmap(0x7f31cbc4a000, 71856) = 0
70791 20:06:34 set_tid_address(0x7f31cb673a10) = 70791
70791 20:06:34 set_robust_list(0x7f31cb673a20, 24) = 0
70791 20:06:34 rt_sigaction(SIGRTMIN, {sa_handler=0x7f31cb67dbf0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f31cb68b3c0}, NULL, 8) = 0
70791 20:06:34 rt_sigaction(SIGRT_1, {sa_handler=0x7f31cb67dc90, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f31cb68b3c0}, NULL, 8) = 0
70791 20:06:34 rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
70791 20:06:34 prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
70791 20:06:34 rt_sigaction(SIGUSR1, {sa_handler=0x561685f53150, sa_mask=[], sa_flags=SA_RESTORER|SA_NOCLDSTOP, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 rt_sigaction(SIGUSR2, {sa_handler=0x561685f54350, sa_mask=[], sa_flags=SA_RESTORER|SA_NOCLDSTOP, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 rt_sigaction(SIGCHLD, {sa_handler=0x561685f530b0, sa_mask=[], sa_flags=SA_RESTORER|SA_NOCLDSTOP, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 rt_sigaction(SIGVTALRM, {sa_handler=0x561685f54390, sa_mask=[], sa_flags=SA_RESTORER|SA_NOCLDSTOP, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 geteuid()                = 0
70791 20:06:34 getegid()                = 0
70791 20:06:34 umask(000)               = 022
70791 20:06:34 umask(022)               = 000
70791 20:06:34 brk(NULL)                = 0x561686200000
70791 20:06:34 brk(0x561686221000)      = 0x561686221000
70791 20:06:34 openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
70791 20:06:34 fstat(3, {st_mode=S_IFREG|0644, st_size=14537584, ...}) = 0
70791 20:06:34 mmap(NULL, 14537584, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f31ca895000
70791 20:06:34 close(3)                 = 0
70791 20:06:34 openat(AT_FDCWD, "/etc/popt", O_RDONLY) = -1 ENOENT (No such file or directory)
70791 20:06:34 openat(AT_FDCWD, "/root/.popt", O_RDONLY) = -1 ENOENT (No such file or directory)
70791 20:06:34 write(2, "rsync: --update: unknown option (in daemon mode)\n", 49) = 49
70791 20:06:34 write(2, "(Type \"rsync --daemon --help\" for assistance with daemon mode.)\n", 64) = 64
70791 20:06:34 rt_sigaction(SIGUSR1, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 rt_sigaction(SIGUSR2, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f31cb6e7210}, NULL, 8) = 0
70791 20:06:34 write(2, "rsync error: syntax or usage error (code 1) at options.c(1455) [client=v3.2.3-133-g512acd12]\n", 93) = 93
70791 20:06:34 exit_group(1)            = ?
70791 20:06:34 +++ exited with 1 +++
`

**Comment by heavyarms2112** [comment]
looks like it complains about --update option?

**Comment by WayneD** [comment]
That means that something badly misconfigured, as that shows something is trying to run rsync with a `--daemon` option and the `--update` option.  The daemon should either be already running, or a daemon-over-ssh instance should be running it will just the `--server --daemon` options (since the user's options are sent over the connection).

**Comment by heavyarms2112** [comment]
@WayneD  Thanks for the update. If there was a configuration issue would that allow rsync to work correctly by changing the directory?

**Comment by heavyarms2112** [comment]
EDIT2: Updating the remote side to a different rsync version (rsync  version 3.1.3  protocol version 31) didn't hit the issue.

**Comment by WayneD** [comment]
For a core dump, you can use gdb to get a backtrace of where it died.  Having debug symbols for the rsync gives you a list of functions that were called and can help to pinpoint the code that is having a problem.

**Comment by Polynomial-C** [comment]
I have a similar looking problem trying to push some files from my local machine with rsync-3.2.4-pre* to two remote machines having rsync-3.2.3 installed:
```
> rsync -e ssh -azc --delete-during --new-compress -q /path/to/source/dir/ user@remoteserver:/path/to/destination/dir
rsync: connection unexpectedly closed (71313 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [generator=3.2.3]
```
So something does not work well here...

**Comment by WayneD** [comment]
Try running without `-z` and/or `./configure --disable-asm` and see if you can narrow it down.

**Comment by Polynomial-C** [comment]
Unfortunately both suggestions didn't help, even in combination. Error message is unchanged.

**Comment by WayneD** [comment]
Read the 2nd comment and follow the instructions on the issues page to get some info from the failing remote rsync.  (My suggestion about recompiling was probably useless, since it sounds like it's the remote 3.2.3 that is causing the problems, not the local 3.2.4.)

**Comment by WayneD** [comment]
I neglected to talk about the `--msgs2stderr` option, which is a good starting point (combined with `-M--msgs2stderr`).  I've started to enhance the [issues page](https://rsync.samba.org/issues.html), which failed to talk about that helpful option.
