### ISSUE TITLE
how to keep owner/group same between two machine

### ISSUE THREAD

**Issue by qqliuxiaoran** [WayneD/rsync#271]
Hello! 
I have two machines, machine A has a user named jackleo(it's me)，machine B also has a jackleo user, but their UID are different(from /etc/passwd). 
A：jackleo:x :1008:1008::/home/jackleo:/bin/bash
B：jackleo:x :1021:1021::/home/jackleo:/bin/bash

Machine A is rsync client, machine B is rsync daemon.
I use following options at machine A:
```
rsync -a -H -A -X -R
```

My rsyncd.conf at machine B as follow:
```
uid=0
gid=0
use chroot=yes
max connections=0
transfer logging=yes
log format=%t %a %m %f %b
syslog facility=local3
port=873
timeout=600
log file=/var/log/rsync/rsyncd.log
dont compress=*.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2

[testModule]
path=/root/test
read only=false
write only=false
list=true
...
```

file(1.txt) at Machine A testModule path:
```
-rw-r--r--  1 jackleo jackleo    0 Jan  4 18:23 1.txt
```

but new file at Machine B doesn't belong to me，It belongs to 1008, but there is no 1008 user on machine B
```
-rw-r--r--  1 1008 1008    0 Jan  4 18:23 1.txt
```
I want this new file at Machine B also belong to ME,  I refer to the documentation carefully but no help.
How should i do?

**Comment by qqliuxiaoran** [comment]
rsync  version 3.2.3  protocol version 31

**Comment by weigx-360** [comment]
I get the same problem, how do you solve?
