### ISSUE TITLE
rsync --update incorrectly reports file "is newer" than itself

### ISSUE THREAD

**Issue by idallen** [WayneD/rsync#297]
Ubuntu told me I had to report this to you.  Go there for all the related environment.

https://bugs.launchpad.net/bugs/1965076

~~~~~
rsync 3.2.3 has a broken "--update" option. See the examples below.
The "--update" option incorrectly makes rsync say a file is newer than itself.
Remove the "--update" option, and rsync correctly says the file is "uptodate".
The right output should of course be "is uptodate" in all cases.
This bug also shows up between machines if the source rsync is 3.1.3 and the destination is 3.2.3.
The bug does not show up if the source rsync is 3.2.3 and the destination is 3.1.3.

$ touch foo
$ rsync -avv --update foo .
delta-transmission disabled for local transfer or --whole-file
foo is newer <=== THIS IS NOT CORRECT - A file can't be newer than itself.
total: matches=0 hash_hits=0 false_alarms=0 data=0
sent 38 bytes received 96 bytes 268.00 bytes/sec
total size is 0 speedup is 0.00

$ rsync -avv foo .
delta-transmission disabled for local transfer or --whole-file
foo is uptodate <=== THIS IS CORRECT
total: matches=0 hash_hits=0 false_alarms=0 data=0
sent 41 bytes received 106 bytes 294.00 bytes/sec
total size is 0 speedup is 0.00
~~~~~

**Comment by WayneD** [comment]
They should have instead told you to test the latest version or at least read the [NEWS file](https://download.samba.org/pub/rsync/NEWS) and notice that it is already fixed.

**Comment by idallen** [comment]
Well - thanks for the quick fix!  :-)

I did do a search for prior reporting of the bug on the Ubuntu bug site (no reports), but forgot to repeat the search here.  I was thinking Ubuntu would have tested the latest version and/or checked for a fix themselves before telling me to report the bug here.  Sorry to bother you.  For those curious, the prior bug report is this one:

    https://github.com/WayneD/rsync/issues/98
