### ISSUE TITLE
Feature Request: completely ignore certain dirs/files

### ISSUE THREAD

**Issue by uli42** [WayneD/rsync#298]
I am running sync to sync two filesets (think of it as kind of a filesystem within a filesystem) on two IBM Spectrum Scale filesystems (GPFS). On the source there's a directory called .snapshots where GPFS will show any system-wide or fileset snapshots to allow for easy access to snapshots. This directory is always there, if there a any snapshopts existing or not. The directory is readonly.

Same is valid for the destination.

My rsync should NOT transfer the data below .snapshots. So in add **--exclude .snapshots**. Fine.

Of course I want an exact copy so I also add **--delete** to the rsync run.

But as I a also need to exclude some other data from a list of filenames/dirnames (which can change from time to time) chances are that such files/dirs exists in the destination. Therefore I need to delete them there. Which leads me to also adding **--delete-excluded**.

Now we have **rsync -auv --delete --exclude-from=<file with excluded dirs/files> --delete-excluded src/ dest/**

The problem with that is that rsync wants to delete .snapshots in the destination, which is always read-only and will always fail, producing an error:
```
rsync: delete_file: rmdir(.snapshots) failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1179) [sender=3.1.2]
```

What I am looking for is an option that excludes given dirs/files without including them into delete-excluded.

**Comment by WayneD** [comment]
Instead of using `--delete-excluded` just use [filter rules](https://download.samba.org/pub/rsync/rsync.1#FILTER_RULES) as they are intended (look for the "hide" rule). That way you're specifying your excludes (which is a shorthand for hide + protect), your hides, and your protects directly.  You could alternately specify an absolute hide & an absolute protect for your .snapshot dir (e.g. `-f H/_/full/path/.snapshots -f P/_/full/path/.snapshots` on any rsync run, which ensures that those rules will never get affected by `--delete-excluded`.

**Comment by uli42** [comment]
Thanks for the pointer, I will surely check the filter rules.

**Comment by WayneD** [comment]
I'll also mention that hide & protect can be alternately specified as a sender-exclude and a receiver exclude (and a normal exclude affects both sides if it's unqualified).  So, a sender-side filter of `-s foo` hides files the same as a `H foo` does, and a `-r foo` protects files on the receiving side the same way that `P foo` does.  Use whatever idiom is most intuitive to you.

**Comment by uli42** [comment]
works like I wanted to have it! Thank you!
