### ISSUE TITLE
Tutorial link on website documentation goes to malware injection site

### ISSUE THREAD

**Issue by arafalov** [WayneD/rsync#299]
On the page: https://rsync.samba.org/documentation.html
The link "A nice tutorial on [setting up ssh to avoid password prompts" (for jdmz . net domain) seems to send a randomly named installer (I am on Mac). The file is zero size, but the behavior seems consistent with malware injection. 

Looking through archive.org, maybe a better destination for link is: https://troy.jdmz.net/rsync/index.html , though that's still on the compromised domain. Or an archive.org link to the original entry.

**Comment by WayneD** [comment]
Thanks for pointing that out!  I did a web search and picked what looked like a nice article on the process. It doesn't mention forced commands like the old one did, but I'll probably look for a separate page for that soon.

**Comment by seamustuohy** [comment]
If you want to keep using the previous content (without the possible malware) then you could link to the Wayback machines archive of that page from 2006. Later archives of the page have the download which arafalov mentioned. But, the 2006 version in the following link just contains the old text. https://web.archive.org/web/20060307123934/http://www.jdmz.net/ssh/
