### ISSUE TITLE
license incompatibility issue (gpl3 with openssl)

### ISSUE THREAD

**Issue by samueloph** [WayneD/rsync#30]
Hello Wayne,

I see that you switched to github for issues and I guess you will also be accepting patches from here, I will be sending some patches that were hanging on Debian for some time soon.

The latest release of rsync (3.2.0) has a licensing issue caused by the addition of the build dependency `libssl-dev`. The problem can be easily solved by adding a OpenSSL exemption on your license definition, as suggested on:
https://lists.debian.org/debian-legal/2004/05/msg00595.html
```
 * In addition, as a special exception, the copyright holders give
 * permission to link the code of portions of this program with the
 * OpenSSL library under certain conditions as described in each
 * individual source file, and distribute linked combinations
 * including the two.
 * You must obey the GNU General Public License in all respects
 * for all of the code used other than OpenSSL.  If you modify
 * file(s) with this exception, you may extend this exception to your
 * version of the file(s), but you are not obligated to do so.  If you
 * do not wish to do so, delete this exception statement from your
 * version.  If you delete this exception statement from all source
 * files in the program, then also delete it here.
```

For more details about the issue, you can refer to:
https://people.gnome.org/~markmc/openssl-and-the-gpl.html
https://lists.debian.org/debian-legal/2002/10/msg00113.html

You might find that other distributions don't care about it, since debian is generally stricter with regards to licensing maters. I really appreciate if you could look into this one.

Thanks,

**Comment by WayneD** [comment]
Did you not read the license? It's already there.

**Comment by samueloph** [comment]
Just noticed that it was changed 13 days ago, I skipped the commit by accident, thanks
