### ISSUE TITLE
[v3.2.4] absolute path resolved as relative to home directory when double-quoted in single quotes

### ISSUE THREAD

**Issue by twojstaryzdomu** [WayneD/rsync#318]
Rsync release 3.2.4 appears to be resolving a double-quoted absolute path enclosed within a single quoted destination as a path relative to a user's home directory.

Quoting the path element should not be affect whether that path is absolute or not.

The overarching single quoting is a result of shell quoting within a ksh shell script. This is done to ensure the destination is properly quoted (to address possible spaces).

The exact command statement from the shell script is as follows:

`rsync "${RSYNC_OPTS[@]}" "${SOURCE}/" "${TARGET}"`

Where `TARGET` is a variable that contains a double quoted component.

The case is equivalent to assigning a variable containing double quotes to another variable, which is later quoted. 

The quoting problem may be reproduced at an interactive shell prompt (bash):
```
# rsync -vvv '-essh -o StrictHostKeyChecking=no -o CheckHostIP=no' /etc/passwd 'username@hostname:"/tmp"'
opening connection using: ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -l username hostname rsync --server -vvve.LsfxCIvu . "\"/tmp\""  (13 args)
[sender] make_file(passwd,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=26808
rsync: [Receiver] change_dir#3 "/home/username/"" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(818) [Receiver=3.2.4]
recv_file_name(passwd)
received 1 names
recv_file_list done
get_local_name count=1 "/tmp"
[Receiver] _exit_cleanup(code=3, file=main.c, line=818): about to call exit(3)
[sender] _exit_cleanup(code=3, file=io.c, line=1667): about to call exit(3)
```
The problem isn't seen with rsync release 3.2.3:
```
# rsync --version
rsync  version v3.2.3  protocol version 31
# rsync -vvv '-essh -o StrictHostKeyChecking=no -o CheckHostIP=no' /etc/passwd 'username@hostname:"/tmp"'
opening connection using: ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -l username hostname rsync --server -vvve.LsfxCIvu . ""/tmp""  (13 args)
[sender] make_file(passwd,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=30628
recv_file_name(passwd)
received 1 names
recv_file_list done
get_local_name count=1 /tmp
generator starting pid=30628
```

The problem seems to occur only when both the single quotes and the double quotes are present. When double quotes are not enclosed in single quotes, it isn't reproducible.
```
# rsync -vvv '-essh -o StrictHostKeyChecking=no -o CheckHostIP=no' /etc/passwd username@hostname:"/tmp"  
opening connection using: ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -l username hostname rsync --server -vvve.LsfxCIvu . /tmp  (13 args)
[sender] make_file(passwd,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=26819
recv_file_name(passwd)
received 1 names
recv_file_list done
get_local_name count=1 /tmp
generator starting pid=26819
```
The issue isn't observed without double quotes:
```
# rsync -vvv '-essh -o StrictHostKeyChecking=no -o CheckHostIP=no' /etc/passwd 'username@hostname:/tmp'            
opening connection using: ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -l username hostname rsync --server -vvve.LsfxCIvu . /tmp  (13 args)
[sender] make_file(passwd,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=26957
recv_file_name(passwd)
received 1 names
recv_file_list done
get_local_name count=1 /tmp
generator starting pid=26957
```

The issue isn't observed when the double quotes are replaced by single quotes. Single quotes preclude parameter expansion in the shell so they're can't act as a possible work-around.
```
# rsync -vvv '-essh -o StrictHostKeyChecking=no -o CheckHostIP=no' /etc/passwd 'username@hostname:'/tmp''
opening connection using: ssh -o StrictHostKeyChecking=no -o CheckHostIP=no -l username hostname rsync --server -vvve.LsfxCIvu . /tmp  (13 args)
[sender] make_file(passwd,*,0)
send_file_list done
send_files starting
server_recv(2) starting pid=30546
recv_file_name(passwd)
received 1 names
recv_file_list done
get_local_name count=1 /tmp
generator starting pid=30546
```

Impacted software versions.
Rsync is self-compiled from 0ac7ebceef70417355f25daf9e2fd94e84c49749.
```
# rsync -V
rsync  version 3.2.4  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs,
    xattrs, optional protect-args, iconv, prealloc, stop-at, no crtimes
Optimizations:
    SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none
# ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
# bash --version
GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)
```

**Comment by WayneD** [comment]
This isn't a bug, this is you specifying incorrect argument values.  To be able to specify broken argument values that you want the remote shell to reinterpret, use the `--old-args` option.

**Comment by twojstaryzdomu** [comment]
I appreciate there is an option to revert to the pre-3.2.4 handling of quoting but would like to understand specifically what is broken about providing a double quoted path?
Double-quoting an absolute path works fine in the shell, which is one of the better lithmus tests. Rsync shouldn't second-guess choices that work widely elsewhere.

**Comment by WayneD** [comment]
There's nothing wrong with double quoting it if you want to keep the shell from interpreting it. What's wrong is that you told rsync that the filename has single quotes in it, which it doesn't. In older versions the remote shell removed the extra quotes.
