### ISSUE TITLE
Please bundle the man page in the tarball

### ISSUE THREAD

**Issue by chdiza** [WayneD/rsync#32]
I tried to build the new rsync on macOS.  After figuring out which --disable-* flags now need to be passed, the configure script bailed out saying that I needed to install some external deps in order to build a man page.

The attempted build is from the distributed tarball and not a GitHub Release or a cloned repo.

I think the manpage should be prebuilt for the regular release source tarball as it used to be.  Otherwise users have to install some heavy deps (python3 at the very least) just to be able to have a man page.

**Comment by chdiza** [comment]
My apologies, I see now that it *is* bundled.

But this points to a bug in the makefile.  `make clean` is wrongly deleting `rsync.1`, which causes the next attempt at building to fail when the configure script thinks it needs to rebuild the manpage.

**Comment by WayneD** [comment]
That's what make clean should do -- remove generated files.  The providing of some generated files is just an added service of the tar file. It's super easy to `pip3 install --user commonmark` or similar to get the man pages to build.
