### ISSUE TITLE
clarify `transfer rule`, `exclude rule` & `file-lists` terms in man page

### ISSUE THREAD

**Issue by twojstaryzdomu** [WayneD/rsync#323]
I found the man page uses several terms that aren't clear to a lay person and are not defined anywhere. These terms are used several times in the man page in different contexts.

The statement:

`This  option is a transfer rule, not an exclude, so it doesn't affect the data that goes into the file-lists, and thus it doesn't affect deletions.`

is not clear without a thorough understanding of the internal execution order of rsync.

The statement implies some sort of rules exist (a transfer rule and an exclude rule). It isn't clear what these mean and how they are different. The difference may be clear to the developer of the option who has a high overview of the internal workflow but not a casual user who isn't privy to it. A definition would be in order.
 
Specifically what is meant here by:

1. The data. Is that something a user specifically provides? The options where this statement appears do not take a parameter.
2. Transfer rule. What is it, when is it performed in the internal workflow?
3. Exclude rule. What is it, when is it performed in the internal workflow?
4. The file-lists. Why in plural? Isn't there a single file list.
5. Not affecting deletions. Do any files get deleted? Is it referring to deletions as a result of a different option? Files are safe from being deleted? For instance, '--update' will overwrite a file, so technically deletions DO take place as part of this option.

Generally, it's better to paraphrase 'affect' to 'perform' and get rid of the the negatives from the statement altogether.

It would be a good idea to have these explained in one place, such as: transfer rule options have this and that impact and list the options of each type.

Another unclear statement:

`It  just  limits the files that the receiver requests to be transferred`

This introduces a cognitive dissonance for a lay person. It's the sender that specifies what is to be transferfed. This statement requires clarification of rsync internals, unnecessary at this point.

It would be better rephrased as:
`It limits the files the sender will be excluding from being sent to the receiver.`
or
`It ensures the sender will exclude the files impacted by the option from transfer.`

Both avoid discussing the internal fact a receiver and a sender reach operate in a consensus model, with the sender creating a proposed file list, vetted by the receiver and sent back to the sender for transfer.

**Comment by WayneD** [comment]
The latest manpage has a bunch of improvements, including:

- https://download.samba.org/pub/rsync/rsync.1#TRANSFER_RULES
- https://download.samba.org/pub/rsync/rsync.1#FILTER_RULES
