### ISSUE TITLE
Build Failure - implicit declaration of function ‘strlcpy’

### ISSUE THREAD

**Issue by orbea** [WayneD/rsync#324]
OS: Gentoo
rsync: https://github.com/WayneD/rsync/commit/6f35553372f262b8024918677645cafd649162e0

Starting with version `3.2.4` the build fails.
```
x86_64-pc-linux-gnu-gcc -I. -I. -I./zlib -g -O2 -DHAVE_CONFIG_H -Wall -W -pedantic-errors  -c flist.c -o flist.o
flist.c: In function ‘send_file_entry’:
flist.c:674:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Wimplicit-function-declaration]
  674 |         strlcpy(lastname, fname, MAXPATHLEN);
      |         ^~~~~~~
      |         strncpy
```
In version `3.2.3` this was only a warning and was not a hard failure.

Since `strlcpy` is a non-standard function the fix is to use `bsd/string.h` instead of the regular `string.h`.
```
diff --git a/rsync.h b/rsync.h
index e5aacd25..05c9d2c5 100644
--- a/rsync.h
+++ b/rsync.h
@@ -336,7 +336,7 @@ enum delret {
 # if !defined STDC_HEADERS && defined HAVE_MEMORY_H
 #  include <memory.h>
 # endif
-# include <string.h>
+# include <bsd/string.h>
 #endif
 #ifdef HAVE_STRINGS_H
 # include <strings.h>
```
Also linking with `-lbsd` might be needed?

The configure `strlcpy` check probably passes because it lacks `-Werror` and thus only emits a warning. Maybe its more obvious to someone familiar with rsync how to modify the build system more cleanly?

Full build log: [rsync.log](https://github.com/WayneD/rsync/files/8837150/rsync.log)

**Comment by WayneD** [comment]
That's pretty weird to segment the declaration into a bsd .h file without segmenting the function itself into a separate library. If configure had not found that strlcpy() existed, rsync would have supplied its own code with its own declaration.

I've made configure look for bsd/strings.h and have rsync.h optionally include it.  Please test that the latest code in git works for you.

**Comment by orbea** [comment]
Yes, I tested the latest commit (https://github.com/WayneD/rsync/commit/b38780f3fdcccd9280452536440e32dec32bade0) and it compiles without warnings, thanks!
