### ISSUE TITLE
Filter pattern matching for "**" not matching when following a slash

### ISSUE THREAD

**Issue by EthanGroat** [WayneD/rsync#325]
I am not 100% sure that this is unintended behavior, however I could find nothing in the documentation, nor any online help, to explain. Quite frankly, filter rules need to be covered better in the man page, with at least an explanation of the precedence / conflict resolution of rules, but that complaint should be for another issue. Sorry, I have issues!

Please forgive me if this is expected behavior. I'm not an expert on pattern matching.

I believe that, if given a directory d and a file in that directory f, then `"d/f"` should be a match with either of the invocations I used here (`"d/**"`, `"d**"`), but when using `"d/**"`, neither d nor f are included. It drove me bonkers. In ls, if I list `"d/**"`, I see every file in d. I assume that the slash should match the slash and the `**` should match any string of characters in path names, including just the one letter `f`, and that is not what is happening here.

```
$ rsync -rv --include="d/**" --exclude="*" testa/ testb
sending incremental file list

sent 39 bytes  received 12 bytes  102.00 bytes/sec
total size is 0  speedup is 0.00
$ rsync -rv --include="d**" --exclude="*" testa/ testb
sending incremental file list
d/f

sent 127 bytes  received 36 bytes  326.00 bytes/sec
total size is 0  speedup is 0.00
```

`"d/*"` is also the same story as `"d/**"`. I don't know what that's all about.

Anyway, thank you for your time. I'm glad I at least figured out how to do what I needed with the simpler "d**" pattern, though that is technically a different pattern.

**Comment by WayneD** [comment]
Use `d/***` (see manpage).

**Comment by Kentzo** [comment]
@EthanGroat `d**` means "d + any number of any characters", so it will cover `d`, `d/f` but also `data/f` etc.

**Comment by EthanGroat** [comment]
> @EthanGroat `d**` means "d + any number of any characters", so it will cover `d`, `d/f` but also `data/f` etc.

That' what I was saying. It didn't match it. Why is that?

> you'd see that the "d" dir gets filtered out and thus d/** doesn't ever see anything to match

why does "d" get filtered out? is that because of the --exclude pattern? It's been so long that I do not remember why that was even there.

**Comment by WayneD** [comment]
https://download.samba.org/pub/rsync/rsync.1#FILTER_RULES
