### ISSUE TITLE
Read error: Connection reset by peer (104)

### ISSUE THREAD

**Issue by Manjuphoenix** [WayneD/rsync#328]
I was trying to mirror a site using rsync but it was failing to some reason and throwed the following error:

**rsync: read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(794) [Receiver=3.1.3]**

The same command worked on different computers without installing any software (including rsync)
About the system (OS : Ubuntu 20.04, rsync version 3.1.3)

**Comment by WayneD** [comment]
For diagnosing connection issues: https://rsync.samba.org/issues.html
