### ISSUE TITLE
Failed test on macOS 10.14.6

### ISSUE THREAD

**Issue by chdiza** [WayneD/rsync#33]
I built the new rsync 3.2.0 from the source tarball using the following flags: --disable-openssl --disable-xxhash --disable-zstd --disable-simd.

(Without those building failed.)

Finally a build succeeded, so I ran `make test`.  One test failed:
```
check how the files compare with diff:

-------------
Failed:  dir-diff
----- atimes log ends
```

**Comment by WayneD** [comment]
Yeah, atimes doesn't seem to be possible on macOS.  Looks like we'll need to disable it in the future.

**Comment by WayneD** [comment]
OK, it's turned off now for macOS.
