### ISSUE TITLE
[RFE] a --disable-gitver configure option

### ISSUE THREAD

**Issue by heitbaum** [WayneD/rsync#355]
Hi Wayne,

Building with the new 3.2.5 "mkgitver" code resulted in rsync version of the LibreELEC git tree - as we build from within the git tree.
```
nuc11:~ # rsync --version
rsync  version 8.95.002-9992-gf0783945  protocol version 31`
```
A quick patch to "blank out the RSYNC_GITVER"

Would be nice to have a `--disable-gitver` configure option?

```
diff --git a/packages/network/rsync/patches/rsync-0001-don-t-set-RSYNC-GITVER.patch b/packages/network/rsync/patches/
rsync-0001-don-t-set-RSYNC-GITVER.patch
new file mode 100644
index 0000000000..ecb7f4791b
--- /dev/null
+++ b/packages/network/rsync/patches/rsync-0001-don-t-set-RSYNC-GITVER.patch
@@ -0,0 +1,11 @@
+--- a/mkgitver 2021-10-01 21:17:53.000000000 +0000
++++ b/mkgitver 2022-08-15 02:11:06.553999692 +0000
+@@ -1,7 +1,7 @@
+ #!/bin/sh
+
+ srcdir=`dirname $0`
+-gitver=`git describe --abbrev=8 2>/dev/null`
++gitver=""
+
+ if [ ! -f git-version.h ]; then
+     touch git-version.h
```

**Comment by WayneD** [comment]
Does it help if mkgitver only runs git describe if .git is in the rsync srcdir?  That's what the latest mkgitver does.  I'm imagining that the rsync source dir is a subdir of the larger git checkout in your case.

**Comment by heitbaum** [comment]
> Does it help if mkgitver only runs git describe if .git is in the rsync srcdir? That's what the latest mkgitver does. I'm imagining that the rsync source dir is a subdir of the larger git checkout in your case.

Perfect - 68b1ce1dc3605a8b79594ba5e8e29577ea6dc42c fixes it - Thank you
