### ISSUE TITLE
rsync v3.2.5 rejecting unrequested file-list name without newline at end of file

### ISSUE THREAD

**Issue by jvilk-stripe** [WayneD/rsync#360]
If you have a file-list that contains at least two items and no newline at the end, rsync 3.2.5 will refuse to sync the final item in the file list.

Workaround is to add a final newline.

Steps to reproduce:

```bash
# Write a file list that does not end in a newline and has at least 2 items
$ echo "file1" >> file-list.txt
$ echo -n "file2" >> file-list.txt
$ cat file-list.txt
file1
file2$ # there's no newline, so the prompt starts here -- good
$ rsync -azrR --files-from=file-list.txt remote-host:/path/to/dir/ /local/path/to/dir
ERROR: rejecting unrequested file-list name: file2
rsync error: protocol incompatibility (code 2) at flist.c(1025) [Receiver=3.2.5]
```

In case it matters, the remote version of rsync is 3.1.3, and I'm rsyncing files from a remote Linux server to a Mac.

**Comment by WayneD** [comment]
Thanks for the report.  This is fixed in a182507bef2d0cd92052b3c5ebaf1d98278e0dad.
