### ISSUE TITLE
--append[-verify] skips source files with new timestamp but same size

### ISSUE THREAD

**Issue by mfeghali** [WayneD/rsync#368]
**SUMMARY:**
Given a file that is the same name and filesize on source and dest, if some bytes are changed in file on source and consequently the date/timestamp is made newer on source machine, file is NOT sent/updated to dest machine, but rather skipped entirely.  If this is by design, please let me know what the rationale is.  If not, please humbly accept my bug report :)

Current behavior:
- If --apend-verify mode is enabled and filesize is identical between source/dest machine, file is SKIPPED even if source timestamp is newer than dest

Desired behavior:
- Only skip files in --append-verify mode if timestamp AND filesize are identical between source/dest machine.  (or maybe if dest >= source timestamp... whichever)

**DETAILS:**
- Use case is to sync VMs and encrypted volumes to a remote machine.  The files do not change size, but when modified, their timestamp will be updated.  The files are usually large (>4GB each, often >100GB), so --partial and --append-verify are very useful...... unless they prevent the file transfer :D
- Source and dest machines both using rsync 3.1.3.
- Used RSYNC protocol (not ssl) to sync data with following options:
--compress
--archive
--times  (I know it's redundant given --archive above)
--delete-after
--recursive
--password-file=xxxxxxxx
--no-perms (tried with and without this to see if any difference; none observed)
--partial
--append-verify

**Comment by WayneD** [comment]
You're using the wrong option. This option is very dangerous for anything other than append-only files, such as log files.

**Comment by mfeghali** [comment]
WayneD, thanks for the feedback.  Why is this option dangerous for non-append-only files?  If I'm "mis-using" --partial and --append-verify in order to resume large file syncs over slow/unreliable network links, isn't that a feature/use-case worth supporting?

**Comment by WayneD** [comment]
It's just not what the option does.  It has a very specific use case.
