### ISSUE TITLE
Unknown --info item: "flist" on tr_TR.utf-8 locale with --progress option

### ISSUE THREAD

**Issue by queeup** [WayneD/rsync#370]
Only occurs with tr_TR.utf-8 locale. Other locales are fine.

```bash
$ LC_ALL=tr_TR.utf-8 rsync  --archive --verbos --progress 1/ 2/
Unknown --info item: "flist"
rsync error: syntax or usage error (code 1) at options.c(467) [client=3.2.5]

$ LC_ALL=tr_TR.utf-8 rsync  --archive --verbose 1/ 2/
skipping directory .

sent 17 bytes  received 12 bytes  58,00 bytes/sec
total size is 0  speedup is 0,00

$ LC_ALL=C rsync --archive --verbose --progress 1/ 2/
skipping directory .

sent 17 bytes  received 12 bytes  58.00 bytes/sec
total size is 0  speedup is 0.00
```

```bash
❯ awk -F= '$1=="PRETTY_NAME" { print $2 ;}' /etc/os-release
"Fedora Linux 36.20220905.0 (Silverblue)"

$ rpm -qa rsync
rsync-3.2.5-1.fc36.x86_64
```

**Comment by serkocal** [comment]
persists in 3.2.7 too, maybe its a i ı İ I problem?

**Comment by WayneD** [comment]
It's apparently a problem with strncasecmp() where `flist` won't match `FLIST`.  I checked-in a change to specify `FLIST2` internally instead of `flist2` when `--progress` is specified.

**Comment by queeup** [comment]
Like @serkocal mentioned, this is because Turkish `i =! I`

As a reference for the future:
https://github.com/util-linux/util-linux/issues/1302
https://github.com/util-linux/util-linux/commit/64a89adaa16461bd58730c1408b30aa7244b4f66
