### ISSUE TITLE
Machine readable (json) output of --version

### ISSUE THREAD

**Issue by buhtzz** [WayneD/rsync#371]
Doing `rsync --version` displays on stdout

```
rsync  version 3.2.3  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, hardlink-specials, symlinks, IPv6, atimes,
    batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv,
    symtimes, prealloc, stop-at, no crtimes
Optimizations:
    SIMD, asm, openssl-crypto
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none
```

This is human- but not machine-readable. Parsing this is possible but not elegant. Would be nice to have a `--json` to print out something like this
```
{
    "version": "3.2.3",
    "protocol": "31",
    "Capabilities": [
        " 64-bit files", "64-bit inums", "64-bit timestamps"
    ],
    "Compress list": [
        "zstd", "lz4", "zlibx", "zlib", "none"
    }
}
```

**Comment by WayneD** [comment]
Seems useful.  I've done something quick [in rsync patches](https://github.com/WayneD/rsync-patches/blob/master/json-version.diff) to be refined for future inclusion.

**Comment by buhtzz** [comment]
Great to hear. Can you please show me an example output of it?

**Comment by WayneD** [comment]
`$ ./rsync -VV`
```json
{
  "program": "rsync",
  "version": "3.2.6-13-g9a49b773",
  "protocol": "31.0",
  "copyright": "(C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.",
  "url": "https://rsync.samba.org/",
  "capabilities": [
    "64-bit files", "64-bit inums", "64-bit timestamps", "64-bit long ints",
    "socketpairs", "symlinks", "symtimes", "hardlinks", "hardlink-specials",
    "hardlink-symlinks", "IPv6", "atimes", "batchfiles", "inplace", "append",
    "ACLs", "xattrs", "optional secluded-args", "iconv", "prealloc",
    "stop-at", "no crtimes"
  ],
  "optimizations": [
    "SIMD-roll", "asm-roll", "openssl-crypto", "no asm-MD5"
  ],
  "checksum_list": [
    "xxh128", "xxh3", "xxh64", "md5", "md4"
  ],
  "compress_list": [
    "zstd", "lz4", "zlibx", "zlib"
  ],
  "license": "GPL3",
  "caveat": "rsync comes with ABSOLUTELY NO WARRANTY"
}
```

**Comment by buhtzz** [comment]
Thank you so much.

**Comment by WayneD** [comment]
FYI, this will be in 3.2.7pre pretty soon, so it will be in the github builds and in the rsync binaries dirs soon.

**Comment by WayneD** [comment]
In the latest git, see the script `support/json-rsync-version` as a way to get the json data from older rsyncs. Only tested back through 3.0.6 at the moment.

**Comment by WayneD** [comment]
FYI, I changed capabilities & optimizations into dictionaries so that someone doesn't need to scan a list for "no crtimes" vs "crtimes".  That's now `"crtimes": true|false`

**Comment by buhtzz** [comment]
Just a sidenote:

Version 3.2.3 (Debian stable) still overs a `-VV` which return the same content as `-V`.
Version 3.1.3: does not offer a `-VV`

Makes a bit hard to detect the json-supporting version of rsync because I can not be sure that `-VV` gives me a json output. ;)

**Comment by WayneD** [comment]
The output is a lot longer when `-VV` is a syntax error (and is on stderr).  If the output doesn't start with a `{` then it's not the json.

The python script is provided as a way to get the json output no matter what the rsync version is.  Install the script somewhere and run the equivalent of `support/json-rsync-version /usr/bin/rsync` (or pipe the `--version --version` output of an rsync into it) and you'll always get json (assuming that python3 is available on the host).

**Comment by buhtzz** [comment]
> The output is a lot longer when `-VV` is a syntax error (and is on stderr). If the output doesn't start with a `{` then it's not the json.

Yes I know. And I have to add checks for that in my code now. And I also found out that `-V` is not provided by 3.1.3
In the end the behaviour of -V , -VV is very different between the rsync versions.

What I know so far now

 - rsync >= 3.2.6: -VV return a json
 - rsync <= 3.2.5 and > (somewhere near) 3.1.3: -VV return the same as -V
 - rsync <= (somewhere near) 3.1.3: -VV doesn't exists
 - rsync == 3.1.3 (Ubuntu 20 LTS) doesn't even know '-V'

> The python script is provided

But I won't ship my application with such a script. At the end I have to parse the output. In my [current code](https://github.com/bit-team/backintime/pull/1300/files#diff-26178aaa6abd0bfceee3ea4ba4d063d9c425cc9ecd6e86fd0c7d5c1f5aa5ff48) I try to extract the rsync version in different ways.

1. Use `-VV` and parse the output for an error message (-VV not exist)
   1. ...parse the output as json.
   2. ...parse the output via regex for the version string.
2. If `-VV` is unknown try a usual `--version` and parse the output via regex for a version string.
