### ISSUE TITLE
allow preserving hard links between source and destination

### ISSUE THREAD

**Issue by ynikitenko** [WayneD/rsync#380]
From `man rsync`:

        --hard-links, -H
            This  tells rsync to look for **hard-linked files in the source**
            and link together the corresponding files on the destination. 

Is it possible to preserve hard links between source *and* destination (when they are on the same file system)?

I make snapshots of my repository, and can move files around. It would be nice to see (when I run `rsync -vHn`) that files in different snapshots are hard linked (because they have same inodes), but at the moment I can see the output like they are deleted and created, like this:

    *deleting   elki/elku_v_ng.jpg
    *deleting   elki/
    .d..t...... ./
    cd+++++++++ rsbor/2017_elki/
    >f+++++++++ rsbor/2017_elki/elku_v_ng.jpg

This does not affect actual changes when I do them (a bit differently), so it is not crucial.

I tried *--fuzzy*, but it didn't find that files had actually same inodes (even with *--no-inc-recursion*), because they have different paths (*--link-dest* is of no use here due to the same reason). As I understand, comparison of hard links is not allowed in `rsync` at the moment. Could it be implemented?

I found that recently *reflinks* became supported (https://github.com/WayneD/rsync/issues/119), so maybe this feature for local directories could be considered as well.

**Comment by WayneD** [comment]
I'd suggest trying `--link-dest=/source/path` so that rsync hard-links everything in the destination dir to the files in the source dir (and no need for `-H`).

**Comment by ynikitenko** [comment]
As I wrote, I tried this option. It doesn't work, because some paths in general don't correspond (they have same inodes, but have different names).

**Comment by ynikitenko** [comment]
@WayneD so pardon, do you consider this an enhancement or do you refuse to do it and close it?

**Comment by WayneD** [comment]
I don't consider it a part of rsync's copying world view.
