### ISSUE TITLE
Invalid error message "rejecting unrequested file-list name"

### ISSUE THREAD

**Issue by stoecker** [WayneD/rsync#382]
When calling
`rsync -R server:/etc/passwd server:/etc/sysconfig/network/ifcfg-eth0 .`
it says
`ERROR: rejecting unrequested file-list name: /etc/sysconfig`
but when I call with the second argument directly it works as expected.

It seems the new invalid path fixes checks ignore second or later path arguments.

See also: https://bugzilla.opensuse.org/show_bug.cgi?id=1203683

Happens with released version in openSUSE and also a freshly compiled git version from today.

**Comment by WayneD** [comment]
Duplicates #376
