### ISSUE TITLE
Two rsync issues: Output contradicts flag + current directory is mistakenly destination

### ISSUE THREAD

**Issue by dafiducka** [WayneD/rsync#383]
I'd like to report about two rsync issues.
Who knows, maybe these are real bugs.

Issues are:
1. The output of rsync contradicts the flag "--out-format" in a
specific scenario.
2. When the destination directory is an empty string, then rsync
thinks that the current working directory is the destination directory
(which is wrong IMHO).

Please see the attached Bash script which shows everything.
The script can reproduce the issue for you.
The script also shows the output that I received in my case.

(I tried to send an email to your mailing list at "rsync@lists.samba.org" but it failed with the message "Delivery Status Notification (Failure)".)

The following is the attached Bash script file which reproduces the issue:
[rsync_issue.txt](https://github.com/WayneD/rsync/files/9691214/rsync_issue.txt)

**Comment by WayneD** [comment]
The `--out-format` is what is output when it is copying. It is never what is output when listing source files with `--list-only` (which is implied if no destination arg is supplied).  If you want to trial the output format, run a `--dry-run` copy with a destination arg (perhaps using a non-existing destination dir).

As for `issue #2`, it looks like you don't know that specifying an empty arg is the same thing as specifying "." to rsync - it's a reference to the current directory.

**Comment by dafiducka** [comment]
Hi Wayne,

Thank you for the quick response.

Regarding issue #1 :
I think it would be beneficial if rsync would include an **additional** log file which shows the "--list-only" files in a format that is chosen by the user.

Regarding issue #2 :
I didn't notice it in rsync manpage.
Isn't it confusing?
Maybe a different function for an empty string will be more helpful.

**Comment by WayneD** [comment]
I have no plans to change the `--list-only` output style.  People can make use of `--dry-run` and (depending on `%i` inclusion in the output format) `-ii` or `-I` to get other forms of output.

I have changed the handling of an empty destination string to be an error (similar to the error for an empty source arg). This new behavior only affects the client and can be avoided using `--old-args` or `RSYNC_OLD_ARGS=1`.
