### ISSUE TITLE
Please document supported filesystem types and limitations

### ISSUE THREAD

**Issue by BillDietrich** [WayneD/rsync#405]
In discussions of "does Timeshift support backing up to exFAT filesystem", I found that the rsync man page says little about filesystem types.  Two mentions of FAT in one place, no mention of exFAT anywhere, not sure about XFS etc.

Some forum articles say alarming things about silently losing ACLs or permissions when using rsync to exFAT.

Please update the rsync man page to say what filesystems are supported and with what limitations.  Thanks.

**Comment by WayneD** [comment]
Yup, rsync doesn't try to explain out all the weird filesystems out there. I'll leave that for someone else to take on.
