### ISSUE TITLE
Ignore_case patch creates an error with mismatch case in directories.

### ISSUE THREAD

**Issue by rosyth** [WayneD/rsync#41]
Sorry, I'm a (old) hardware man, so I'm not very familiar with all the 'protocols' around fixing software these days.
I don't intend to spend a week or so learning all the howto's of git / patch / etc etc etc.  So sorry,  but I've fixed it for myself (as far as I need it)  this is to give someone else a chance to benefit from my fix.

I applied the patch 'ignore-case.diff' from 'rsync-patches-3.2.0.tar.gz' to the code in 'rsync-3.2.0.tar.gz' on LinuxMint 19.3,
Mostly it works,  till today,  trying to sync my music library with a copy on an external hard drive.  I get this error.
Using the --ignore-case  switch
> ABORTING due to invalid path from sender: 1977 - Songs from the wood - Jethro Tull/01 - Songs From the Wood - Jethro Tull.flac [receiver=3.2.0]
What I see is that the two file paths differ in case in the Directory too, eg.
Target Dir has.
drwxr-sr-x 3 abcd users 4096 Jun  6  2014 1977 - Songs from the wood - Jethro Tull
drwxr-sr-x 2 abcd users 4096 Jun  6  2014 1977 - Songs from the Wood - Jethro Tull
drwxr-sr-x 2 abcd users 4096 Jun  6  2014 1977 - Songs From The Wood - Jethro Tull
Source Dir has.
drwxrwxrwx 1 abcd abcd 4096 Jun  6  2014 1977 - Songs from the wood - Jethro Tull
drwxrwxrwx 1 abcd abcd 4096 Jun  6  2014 1977 - Songs from the Wood - Jethro Tull
drwxrwxrwx 1 abcd abcd 4096 May 30  2012 1977 - Songs From The Wood - Jethro Tull

I managed to fix this with one line (in the patched file).
The message is created from a mismatch in the directory names at flist.c at line 2557
[flist-fix-ignore-case-patch.txt](https://github.com/WayneD/rsync/files/4840931/flist-fix-ignore-case-patch.txt)

Hope this is of use.

**Comment by WayneD** [comment]
Thanks!  I've committed a fix the rsync-patches repo.
