### ISSUE TITLE
`rsync-no-vanished` incorrectly treating files called `\nfile has vanished: ` .

### ISSUE THREAD

**Issue by lockywolf** [WayneD/rsync#410]
We are using rsync-no-vanished to backup some user directories, and found unexpected behaviour in the logs when rsync was not reporting some problems with file transfer. After some investigation we found that our user has files called "\nfile has vanished: XXXX" (That is the beginning of line character, not a literal \n.), which is (incorrectly) filtered out by grep. 

Could --info=vanish0 be added so that this warning would be filtered away on rsync level, instead of relying on grep?

**Comment by WayneD** [comment]
Firstly if there were a newline at the start of the filename, rsync would display the name as `\#012file...`.  To avoid an issue with a file w/o the ctrl char, use `-i` (`--itemize`) or an `--out-format`.
