### ISSUE TITLE
Add option to copy just metadata

### ISSUE THREAD

**Issue by dg1727** [WayneD/rsync#42]
Suggestion:  Add an option (maybe `--metadata-only`) which will copy **only metadata** from a specified existing file, folder, or dirtree to a specified existing file, folder, or dirtree.  

My use case involves copying metadata from only 1 existing source file or folder to 1 existing target file or folder (not to files or folders that may be within the target folder).  I intend to use rsync for this at various points within a script.  

A comment to https://askubuntu.com/a/150888 points out an existing option that is similar to what I'm asking for:  
> --archive --size-only is a great combo. Not only does it prevent recopying files that already exist in the destination, but it will also update their metadata. This was unexpected for me, because rsync's man page describes --size-only as "skipping" files whose sizes match. Turns out that it just skips the copy, but will still sync the metadata.  

I'd prefer an option whose name & manpage description are more applicable (than --size-only) to my use case.  For example, I don't need that rsync should "detect whether" to copy the metadata; I need rsync to copy the metadata to the target file or folder unconditionally.  Also, the name & the manpage description of the relevant option (--metadata-only or whatever) should be about metadata specifically; avoiding, for example, the possibility of copying any **contents** to the target file or folder.  

My interests about what metadata to copy are as follows:  
- For certain, what I need copied includes owning user, owning group, the Unix classic permissions bits (rwxrwxrwx + sticky bits & setuid), and all extended attributes (xattrs) that are on the source file or folder.  
- It is OK if I need to specify another option at the same time, to modify --metadata-only (or whatever it ends up being called) to get xattrs copied.  
- I'm not asking for any of atime, btime, ctime, mtime to be copied.  For instance, the target file or folder may have different contents than the source, so copying "the time the contents were modified" to be the same as the source mtime isn't necessarily meaningful.  
- File or folder **name** should definitely NOT be copied.  

I look forward to your comments.  

BTW, I looked through recent issues & I noticed that WayneD and the other contributors have been jumping right onto reported bugs.  That's first-rate.  :thumbsup:

**Comment by WayneD** [comment]
Sorry, I don't think this option is a good match for rsync.

**Comment by Semnodime** [comment]
> Sorry, I don't think this option is a good match for rsync.

@WayneD, Please elaborate.
