### ISSUE TITLE
[ArchLinux, v3.2.7] This rsync does not support --crtimes (-N)

### ISSUE THREAD

**Issue by Perdu** [WayneD/rsync#420]
I'm having this issue on Arch Linux with rsync version 3.2.7

$ rsync -avN somefile.jpg /somedir/somefile.jpg
rsync: This rsync does not support --crtimes (-N)
rsync error: syntax or usage error (code 1) at main.c(1791) [client=3.2.7]

Both source and destination partitions are ext4, if that matters

**Comment by WayneD** [comment]
Linux has traditionally not supported creation times. There has been some progress made in recent years on accessing the birth tiime that some filesystems set by using a fairly new system call "statx()", but I know of no way to set the btime other than to create the file.  If someone knows the answer to that, please let me know.

**Comment by Perdu** [comment]
Would it be a good idea to document the level of support of different systems then? There seems to be discrepancies between Linux, MacOS, FreeBSD and others

**Comment by WayneD** [comment]
I've just mentioned in the manpage that support is conditional.
