### ISSUE TITLE
Can we get an --info=REASON option (why does rsync think a file should be synced/transferred)

### ISSUE THREAD

**Issue by reikred** [WayneD/rsync#438]
I found myself surprised when rsync wanted to update (transfer) a fairly large number of files, although I expected very few.

Instead of me going through manually all the files to see if I could spot the reason(s), I thought it would be useful if rsync itself would have an option to list for each file the REASON why rsync thinks any specific  file should be updated.

1. data reason, with some detail (i.e. detail about mismatch in size or checksum or modification date) (list all valid reasons)
2. metadata reason, with some detail (i.e. detail about why rsync wants to change the owner or date or whatnot)

Something like --info=REASON would work for me.

I have searched the manual and cou;d not find any option to do what I want, but please please correct me if I missed something.

**Comment by WayneD** [comment]
Use `--itemize` (`-i`).

**Comment by reikred** [comment]
That is an totally awesome option. I love the format of the REASONs for an update.

Note to self: Quick guide to the field names and meanings:

```
YXcstpoguax == Yupdatetype Xfiletype checksum size time permissions owner group usetime/newness/both acl xtendedattribute
"+" - the file does not exist at dest, and all the attrributes are being created
Example:
>f.st...... boot/grub/grub.cfg

```
