### ISSUE TITLE
rsync unpredictably does mass random deletes when executed as a python subprocess

### ISSUE THREAD

**Issue by jer826** [WayneD/rsync#439]
When running rsync as a python subprocess and passing one subprocess parameter as an empty string, rsync will mass delete files and folders in the current working directory unpredictably. Code below.

```
dry_run = False

if not dry_run:
    dry_run_arg = ""
else:
    dry_run_arg = "--dry-run"

bk_args = "-abv"
bk_src_dir = "/home/jer/_d1/"
bk_tar_dir = "/home/jer/_d2"
bk_delta_dir = "/home/jer/_cd/changed_deleted"
bk_logfile = "/home/jer/backup.log"

subprocess.run(["rsync", bk_args, "--backup-dir=" + bk_delta_dir,  "--log-file=" + bk_logfile, "--log-file-format=%i %o %f", bk_src_dir, bk_tar_dir, "--itemize-changes=%i%f", "--info=stats2", "--delete", dry_run_arg])
```

When variable dry_run = False, dry_run_arg = "" (empty string). In the subprocess call to rsync, when the last parm (dry_run_arg is an empty string, unpredictable mass random deletes occur in the current working directory.

**Comment by WayneD** [comment]
The empty arg is a synonym for the current directory in older rsync versions (it's rejected in newer versions).

The ultimate issue is that you can't specify random args to a program.  In python, use `dry_run_arg = []` or `dry_run_arg = ["--dry-run"]` in the "if" and reference the array using `*dry_run_arg` in the list to expand it into 0 or 1 arg.

**Comment by jer826** [comment]
Thanks for the information Wayne.  For completeness on this thread, I wanted to document that I am running rsync version 3.2.3.
Seems like it would be more reasonable for rsync to respond with an error, if the arguments were not correct.

**Comment by WayneD** [comment]
The mentioned changed handling for making an empty argument an error is quite new (3.2.7).
