### ISSUE TITLE
@ERROR: chdir failed (daemon failure due to new systemd ProtectHome=on restriction)

### ISSUE THREAD

**Issue by filipsPL** [WayneD/rsync#44]
As a follow up for issue #43. After applying changes, I get a new error:

Client (rsync  version 3.1.3  protocol version 31):
```bash
rsync -av --password-file=pa.txt file.png  rsync://user@host/dir/
@ERROR: chdir failed
rsync error: error starting client-server protocol (code 5) at main.c(1675) [sender=3.1.3]
```

Server (rsync  version 3.2.1  protocol version 31):
```
2020/07/01 09:00:40 [2017875] rsync: [Receiver] chdir /home/localdir failed: No such file or directory (2)
```

All directories mentioned above exist. When downgrading to rsync 3.1.3 everything works fine.

**Comment by WayneD** [comment]
I imagine that you're running that under systemd? The default config was tightened up to set `ProtectHome=on` by default, so you should run something like `sudo systemctl edit rsync` and specify:

```
[Service]
ProtectHome=off
```

Or you might consider moving the dir out from under /home (whatever you prefer).

**Comment by WayneD** [comment]
I've committed the change to turn this off.
