### ISSUE TITLE
Invalid source dir list when source dir argument end in /.*/

### ISSUE THREAD

**Issue by jer826** [WayneD/rsync#448]
I would like to copy only the hidden files and folders in my home directory with rsync.
Running the following command from the terminal:

rsync -av --dry-run /home/jer/.*/ /mnt/md0

Produces the following (partial) results:

>f+++++++++ jer/.var/app/com.jetbrains.PyCharm-Community/data/virtualenv/wheel/house/setuptools-67.4.0-py3-none-any.whl
>f+++++++++ jer/.var/app/com.jetbrains.PyCharm-Community/data/virtualenv/wheel/house/wheel-0.38.4-py3-none-any.whl
>f+++++++++ jer/.var/app/com.jetbrains.PyCharm-Community/data/virtualenv/wheel/house/wheel-0.38.4-py3-none-any.whl.lock
cd+++++++++ jer/Backup/
cd+++++++++ jer/Backup/AppConfig/
cd+++++++++ jer/Backup/AppConfig/Brave/

Note that after rsync searches the  dot directories, it start searching all of the non-dot (non-hidden) directories.
Is this a bug or does using the ".*" sequence require some special handling?

**Comment by WayneD** [comment]
The `.` directory is matched by `.*` in bash.  You could switch to zsh or specify something like `.?*` or `.[a-z]*`.
