### ISSUE TITLE
rsync 3.2.7 has problems with list of paths in curly braces

### ISSUE THREAD

**Issue by geg-mopo3** [WayneD/rsync#457]
The following script stopped working after upgrade to version **3.2.7-0ubuntu0.22.04.2**

```
#!/bin/bash
REMOTE_HOST="$1"

if [ "$#" == 0 ]; then
  printf "Usage:
  parameter 1: host ip (for example: 192.168.1.65)
"
  exit 0
fi

COMMON_PATHS="{\
/home/den/.android,\
}"

REMOTE_PATHS="$REMOTE_HOST:$COMMON_PATHS"

rsync -aAXvRO --delete "$REMOTE_PATHS" /
```

I could successfully use it, e.g.:

> $ rsync-with-remote-host.sh 192.168.1.67

But after the upgrade to the above version I began to get the error:

> den@192.168.1.67's password:
> receiving incremental file list
> rsync: [sender] link_stat "/home/den/{/home/den/.android,}" failed: No such file or directory (2)
> 
> sent 8 bytes  received 8 bytes  2,91 bytes/sec
> total size is 0  speedup is 0,00
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1865) [Receiver=3.2.7]
> rsync: [Receiver] write error: Broken pipe (32)

After I downgraded rsync to the previous version **3.2.3-8ubuntu3** the script worked again

**Comment by WayneD** [comment]
Remove curly brace expansion isn't supported without trusting the remote host.  See: [`--old-args`](https://download.samba.org/pub/rsync/rsync.1#opt--old-args)
