### ISSUE TITLE
rsync error: syntax or usage error (code 1) at main.c(2594) [Receiver=3.0.7]

### ISSUE THREAD

**Issue by bugsexplorers** [WayneD/rsync#460]
Bug description
Get error "rsync error: syntax or usage error (code 1) at main.c(2594) [Receiver=3.0.7]" when connected to NAS Synology TS-228A thought SSH.

Steps to reproduce
1) Open putty
2) Connect to NAS via SSH
3) Enter command: rsync -vv 
4) Get error

Expected behavior:
Get information about the version of the running service

Actual behavior:
Get error "rsync error: syntax or usage error (code 1) at main.c(2594) [Receiver=3.0.7]"

Rsync Version:
3.0.7

Additional context:
I noticed this when I updated the system to the latest firmware.

**Comment by WayneD** [comment]
That is because that is a bogus command. Perhaps you meant to type `rsync --version`. On rsync 3.2.0 and newer you can use `-V` (which isn't `-v`) as an alias for `--version`.

**Comment by bugsexplorers** [comment]
Command###  rsync --version also gets error "rsync error: syntax or usage error (code 1) at main.c(2594) [Receiver=3.0.7]"

**Comment by christianrickert** [comment]
```terminal
rsync
```
without parameters also seems to a bogus command for rsync 2.6.9. on macOS Sonoma 14.7.1 - in this (old) version, the output is identical to `rsync --help`, followed by error (code 1) as well:
```terminal
rsync  version 2.6.9  protocol version 29
Copyright (C) 1996-2006 by Andrew Tridgell, Wayne Davison, and others.
<http://rsync.samba.org/>
Capabilities: 64-bit files, socketpairs, hard links, symlinks, batchfiles,
              inplace, IPv6, 64-bit system inums, 64-bit internal inums

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

[shortened]

Use "rsync --daemon --help" to see the daemon-mode command-line options.
Please see the rsync(1) and rsyncd.conf(5) man pages for full documentation.
See http://rsync.samba.org/ for updates, bug reports, and answers
rsync error: syntax or usage error (code 1) at /AppleInternal/Library/BuildRoots/289ffcb4-455d-11ef-953d-e2437461156c/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(1322) [client=2.6.9]
```
Just in case someone runs across the same error on their terminal.
