### ISSUE TITLE
Receiving with current rsync 3.2.7 and current macOS 13.3 fails: error in rsync protocol data stream (code 12)

### ISSUE THREAD

**Issue by wq9578** [WayneD/rsync#462]
The current rsync installed with homebrew fails in copying a directory locally, while the original version shipped with macOS works as well as the homebrew version on an older macOS.
Also, receiving from remote servers fail, while sending works.

macOS 13.3:
```
$ /opt/homebrew/bin/rsync -av dir1 dir2 
sending incremental file list
rsync: connection unexpectedly closed (77 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [generator=3.2.7]
rsync: connection unexpectedly closed (5 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]
$ /opt/homebrew/bin/rsync --version    
rsync  version 3.2.7  protocol version 31
[...]
$ /usr/bin/rsync -av dir1 dir2
building file list ... done
dir1/random.bin

sent 1048841 bytes  received 42 bytes  2097766.00 bytes/sec
total size is 1048576  speedup is 1.00
$ /usr/bin/rsync --version    
rsync  version 2.6.9  protocol version 29
[...]
$ sw_vers 
ProductName:		macOS
ProductVersion:		13.3
BuildVersion:		22E252
```

macOS 11.3.1:
```
$ /opt/homebrew/bin/rsync -av dir1 dir2     
sending incremental file list
created directory dir2
dir1/
dir1/random.bin

sent 1.048.963 bytes  received 66 bytes  2.098.058,00 bytes/sec
total size is 1.048.576  speedup is 1,00
$ /opt/homebrew/bin/rsync --version         
rsync  version 3.2.7  protocol version 31
[...]
$ sw_vers                          
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```

**Comment by WayneD** [comment]
You'll need to contact the homebrew folks and ask them how they messed up rsync.  I'd imagine they're applying one or more patches to it.

**Comment by fxcoudert** [comment]
The only patch we're applying is `fileflags.diff`
We configure with the following flags:

```
      --disable-debug
      --prefix=#{prefix}
      --with-rsyncd-conf=#{etc}/rsyncd.conf
      --with-included-popt=no
      --with-included-zlib=no
      --enable-ipv6
```

then run `make && make install`.

**Comment by WayneD** [comment]
I imagine if you remove fileflags.diff that all should be well. The fileflags.diff patch is definitely not tested by me.

**Comment by fxcoudert** [comment]
I have been unable to reproduce the reported issue, despite using the same macOS version and same build. Not sure where it originates…

**Comment by wq9578** [comment]
@WayneD Feedback from homebrew:

> So the issue does not come from the patch, and we cannot reproduce it on our own machines (the test passes on all CI machines, and your example passes on mine). There is definitely something occurring that is specific to your machine, but it's hard to know what. I would recommend asking rsync authors for directions to debug it.

https://github.com/Homebrew/homebrew-core/issues/129732#issuecomment-1529718725

**Comment by carlocab** [comment]
> I imagine if you remove fileflags.diff that all should be well. The fileflags.diff patch is definitely not tested by me.

Removing the `fileflags.diff` patch did not fix the issue. https://github.com/Homebrew/homebrew-core/issues/129732#issuecomment-1529711900

That said, neither I, nor @fxcoudert can reproduce the problem, and this doesn't occur in our CI either.
