### ISSUE TITLE
total files reported in stats differs for rsyncd

### ISSUE THREAD

**Issue by gklanderman** [WayneD/rsync#47]
Hi Wayne, this is pretty minor but has bugged me for a long time.. I'm backing up to two locations, one local accessing directly, and a second remote using rsyncd.  I've noticed that the 'Number of files' output by the --stats summary differs in these two cases; the 'Number of regular files transferred', 'Total file size', and 'Total transferred file size' do agree.  I'm using an rsnapshot summarizer, for example:

```
SOURCE                TOTAL FILES   FILES TRANS      TOTAL MB     MB TRANS
--------------------------------------------------------------------------
/home/                     322600            65     264848.91       135.81
/music/                     30107             0     240162.43         0.00
/etc/                        1435            10          7.69         0.16
/root/                        322             0          1.79         0.00
/build/                    453006             0       9235.40         0.00
--------------------------------------------------------------------------
TOTAL                      807470            75     514256.20       135.98
```

vs

```
SOURCE                TOTAL FILES   FILES TRANS      TOTAL MB     MB TRANS
--------------------------------------------------------------------------
rsync://lwm/home           356528            65     264848.91       135.81
rsync://lwm/music           32758             0     240162.43         0.00
rsync://lwm/etc              2967            10          7.69         0.16
rsync://lwm/root              524             0          1.79         0.00
rsync://lwm/build          485837             0       9235.40         0.00
--------------------------------------------------------------------------
TOTAL                      878614            75     514256.20       135.98
```

**Comment by gklanderman** [comment]
aargh meant to say this appears unchanged in 3.2.1

**Comment by WayneD** [comment]
At a guess, maybe the second one counts dirs as files and the first one does not.  Is the daemon's rsync kinda old?

(Also, don't forget that there is an edit option in the 3-dot menu if you want to tweak something after you hit Comment.)

**Comment by gklanderman** [comment]
Yeah I was guessing that the rsyncd case might be counting the directories.  The daemon's rsync is current (upgraded to 3.2.1 last Friday, and 3.1.3-8 previously).  But the client is pretty old, 3.0.9-4.  Running some  tests with both client and server using 3.2.1 I am seeing the count match, so I will close this.  Sorry for the noise.. and yeah I should really upgrade that ancient RPi in the basement..
