### ISSUE TITLE
URLs in manual page should be marked with .UR .UE macros

### ISSUE THREAD

**Issue by fernape** [WayneD/rsync#472]
In the `rsync` manual page the different URLs are not marked as such. Hence some tools might consider the URL and the trailing dot `.` at the end of the sentence as part of such URL resulting in a 404 HTTP code.

In [This FreeBSD PR](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270803) there is [a patch](https://bugs.freebsd.org/bugzilla/attachment.cgi?id=241455) to address the issue. This way the URLs are properly surrounded by `<` and `>` symbols.

The final fix though might be done in [md-convert](https://github.com/WayneD/rsync/blob/master/md-convert) by I'm not familiar with the tool :-)

**Comment by WayneD** [comment]
That seems like a nice idea to me so I coded up a change to my md-convert script. There may be a problem on systems that don't support the macros, so if it turns out to cause an issue I'll need to look into making the macros optional.

**Comment by fernape** [comment]
> That seems like a nice idea to me so I coded up a change to my md-convert script. There may be a problem on systems that don't support the macros, so if it turns out to cause an issue I'll need to look into making the macros optional.

Thanks!
