### ISSUE TITLE
Windows Binaries Pretty Please?

### ISSUE THREAD

**Issue by a-raccoon** [WayneD/rsync#48]
Hello @WayneD ,

I wish to appeal to you for official rsync Windows binaries, to be included with the stable releases available on this GitHub.  Rsync is a great tool, but difficult to access for us Windows users without pre-compiled binaries or package managers.

Thanks in advance for your consideration.

**Comment by WayneD** [comment]
Cygwin releases rsync for Windows if you want to go that route.  I don't release any binaries at all.

**Comment by benrubson** [comment]
Note that Cygwin binary now has all features enabled, including xxhash :
https://cygwin.com/packages/summary/rsync.html

**Comment by a-raccoon** [comment]
> Note that Cygwin binary now has all features enabled, including xxhash :
> https://cygwin.com/packages/summary/rsync.html

Of note, I don't think cygwin emulated software will ever be capable of manipulating Sparse Files. It's not a pass-through capability of the emulation layer.  Because of this, a friend wrote a small 'sparsify' windows c exe for me that converts normal while files into sparse files in the same way rsync and gnu cp does.

**Comment by AlttiRi** [comment]
https://gist.github.com/hisplan/ee54e48f17b92c6609ac16f83073dde6#gistcomment-3605244
