### ISSUE TITLE
11eb67eec9b4d990ae4df680cf7db77dad1b8630 broke  --bwlimit=0

### ISSUE THREAD

**Issue by kenshin33** [WayneD/rsync#51]
according the to man page (https://github.com/WayneD/rsync/blob/master/rsync.1.md) a value of 0 passed to  --bwlimit means unlimited. 11eb67eec9b4d990ae4df680cf7db77dad1b8630 broke that behavior ass seen here:

     $ rsync  --bwlimit=0  /source/ /dest/
     rsync: --bwlimit value is too small: 0
     rsync error: syntax or usage error (code 1) at main.c(1694) [client=3.2.2]

**Comment by WayneD** [comment]
The change in 5dcb49c7 fixes this. Thanks for the report!
