### ISSUE TITLE
On 32bit host, I get --max-alloc value is too big: 4G

### ISSUE THREAD

**Issue by realsimix** [WayneD/rsync#52]
We're running backups with `rsync -H` on multi-million files from multiple servers to a central storage. For this to work we have to increase the memory with the new `--max-alloc` option. While this works fine for most systems, there are still a number of 32bit systems around and now rsync fails on them.

From what I understand this is expected and the maximum possible value is `--max-alloc=2G-1` for these hosts.

Now in our case it would be extremely helpful if rsync would not exit with an error in such a case but reduce the max-alloc value to the largest possible value and only print a warning about it.

That way our transfers could always use `--max-alloc=4G-1` without knowing if one side is an old 32bit platform.

This is a small feature request and it would really be nice to have it. If there are better ways to solve our problem I appreciate to hear it.

Thanks,
Simon

**Comment by WayneD** [comment]
The latest git commit allows you to use `--max-alloc=0` for unlimited (can also be set via environment).
