### ISSUE TITLE
Failed to find packages that are installed

### ISSUE THREAD

**Issue by jzadra** [WayneD/rsync#524]
After running `./configure`, I get the errors:

Configure found the following issues:

- Failed to find openssl/md4.h and openssl/md5.h for openssl crypto lib support.
- Failed to find xxhash.h for xxhash checksum support.
- Failed to find zstd.h for zstd compression support.
- Failed to find lz4.h for lz4 compression support.

However, they are installed:

![image](https://github.com/WayneD/rsync/assets/25590353/d215704c-1456-4bec-b526-1c6c3eabaf9a)

System info:
OSX 13.5
rsync 3.2.7

**Comment by rajeshbeats** [comment]
This worked for me on Sonoma 
After installing the packages try this.

`./configure CPPFLAGS="-I/opt/homebrew/Cellar/xxhash/0.8.2/include -I/opt/homebrew/Cellar/zstd/1.5.5/include -I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.1.3/include" LDFLAGS="-L/opt/homebrew/Cellar/xxhash/0.8.2/lib -L/opt/homebrew/Cellar/zstd/1.5.5/lib -L/opt/homebrew/Cellar/lz4/1.9.4/lib -L/opt/homebrew/Cellar/openssl@3/3.1.3/lib"`
this worked for me.

**Make sure to replace the path from your local machine `xxhash`, `lz4` , `zstd`, `openssl`**

**Comment by jzadra** [comment]
That did the trick!
