### ISSUE TITLE
FreeBSD patches

### ISSUE THREAD

**Issue by benrubson** [WayneD/rsync#60]
Hi,

In current FreeBSD [rsync port](https://www.freshports.org/net/rsync) version (3.1.3), there are various patches.

Here they are, so that we can decide whether or not they should be included here.

~`extrapatch-main.c`, included when `patches/fileflags.diff` is enabled :~
[extrapatch-main.c.txt](https://github.com/WayneD/rsync/files/4908278/extrapatch-main.c.txt)

~`patch-siginfo`, whichis , as per my findings, never included, could be an old file in the port archive...~
[patch-siginfo.txt](https://github.com/WayneD/rsync/files/4908275/patch-siginfo.txt)

`extrapatch-acl`, included when `patches/acls.diff` is enabled :
[extrapatch-acl.txt](https://github.com/WayneD/rsync/files/4908277/extrapatch-acl.txt)

Will be useful to @rosorio, the package maintainer.

Thank you 👍

**Comment by WayneD** [comment]
The extern in the main.c patch was already fixed in fileflags.diff. The siginfo feature was already added to the master branch. The acl patch is interesting, but a **horrible** implementation that makes the affected rsync totally incompatible with an official rsync when using the -A option (they add an extra int into the protocol stream that will cause an unpatched rsync to totally crash and burn). It would be interesting to look into support nfs4 acls in a proper manner.

**Comment by igpit** [comment]
> The extern in the main.c patch was already fixed in fileflags.diff. The siginfo feature was already added to the master branch. The acl patch is interesting, but a **horrible** implementation that makes the affected rsync totally incompatible with an official rsync when using the -A option (they add an extra int into the protocol stream that will cause an unpatched rsync to totally crash and burn). It would be interesting to look into support nfs4 acls in a proper manner.

so you are saying that using the FreeBSD-package version with --acls will not work when talking to a rsync on like debian? or does the FreeeBSD-package version not include that patch like the ports do?

**Comment by WayneD** [comment]
I not familiar enough with FreeBSD to answer such a question.

**Comment by benrubson** [comment]
Closing this, as `patches/acls.diff` has now been removed from FreeBSD rsync port.
@rosorio, `patches/extrapatch-main.c` still exists, but I think you can safely remove it, it even does not apply to the source tree anymore...
Thx 👍
