### ISSUE TITLE
clang: note: diagnostic msg

### ISSUE THREAD

**Issue by TonyTTTT** [WayneD/rsync#78]
macOS 10.15.6
Mac mini (2018)
3.2 GHz 6-Core Intel Core i7

Will compile with ./configure with --disable-simd

clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/nq/rvbx8hvx4xd0csp9mtf2cldc0000gn/T/simd-checksum-x86_64-863194.cpp
clang: note: diagnostic msg: /var/folders/nq/rvbx8hvx4xd0csp9mtf2cldc0000gn/T/simd-checksum-x86_64-863194.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/Tony/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
If you can't fix the issue, re-run ./configure with --disable-simd.

**Comment by WayneD** [comment]
Note that they're telling to you notify the clang people, not me.  I believe the issue has already been reported, though.

**Comment by TonyTTTT** [comment]
Sorry about that...
