### ISSUE TITLE
maintained versions

### ISSUE THREAD

**Issue by carlwgeorge** [WayneD/rsync#80]
What does the project consider a maintained version?  Some projects such as PHP and Python declare support for each X.Y version, with defined end of life dates.  Others like Redis maintain the current and previous major versions.  Other projects don't use this concept at all, and just release continuously higher new versions.  What is the rsync approach to versioning?

To rephrase with a specific example, if a security vulnerability was discovered that affected rsync 3.1.3, would the fix only be included in the next 3.2.x version, or would a new 3.1.4 version be released?  I'd like to know because I maintain the rsync31 RPM package in the [IUS](https://ius.io) repository, which provides version-named packages as alternatives to the older versions typically included in RHEL and CentOS.  If there will never be another 3.1.x version, I plan to retire the rsync31 package.  I could create a replacement rsync32 or rsync3 package as appropriate.

**Comment by WayneD** [comment]
I only release new versions.  Some distributions backport fixes into their older versions, and I have been known to help them out with their questions about how security changes affect an older version.

**Comment by carlwgeorge** [comment]
Understood, thanks for the clarification.  IUS doesn't do backports, we just follow the upstream versions, restricted by what we name the package.  I'll retire rsync31, and if there is still demand for a newer rsync than provided in RHEL then I'll work on an rsync3 package that can follow new releases until a hypothetical breaking 4.x.x version.
