### ISSUE TITLE
rsync -v: say if no changes were made

### ISSUE THREAD

**Issue by jidanni** [WayneD/rsync#82]
Let's take a look at rsync -v output:

```
sent 433 bytes  received 1,162 bytes  354.44 bytes/sec
total size is 44,983  speedup is 28.20
```

A second run reveals

```
sent 20 bytes  received 63 bytes  23.71 bytes/sec
total size is 44,983  speedup is 541.96
```

A third run reveals

```
sent 20 bytes  received 63 bytes  18.44 bytes/sec
total size is 44,983  speedup is 541.96
```

OK, that is great, but all this info misses the main point:

On the second and third runs it should also say
"**No changes made**", "**Files already (r)synced, nothing to do.**", etc.

Sure, the savvy user will know
"_sent 20 bytes  received 63 bytes_"
are the two magic numbers via which the pros can tell that no changes were made,
but why not cough up that fact that no changes were made in the -v messages?
It seems more significant than exact bytes per second decimals, etc.

rsync  version 3.2.3  protocol version 31

**Comment by WayneD** [comment]
Use --stats for more info.

**Comment by jidanni** [comment]
OK but now with --stats, it is even _less_ clear which run didn't change anything.

```
Number of files: 1 (reg: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 1
Total file size: 44,983 bytes
Total transferred file size: 44,983 bytes
Literal data: 0 bytes
Matched data: 44,983 bytes
File list size: 52
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 433
Total bytes received: 366

sent 433 bytes  received 366 bytes  177.56 bytes/sec
total size is 44,983  speedup is 56.30
```
vs.

```
Number of files: 1 (reg: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 0
Total file size: 44,983 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 52
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 20
Total bytes received: 63

sent 20 bytes  received 63 bytes  18.44 bytes/sec
total size is 44,983  speedup is 541.96
```

OK maybe
```
Number of regular files transferred: 0
```
is the line that is telling us that
"No files needed updating"
But
1. it is buried within all those other lines.
2. it isn't as clear as just also saying "No files needed updating"

As far as
> it's the lack of any mentioned file names that indicates that there were no copied files.

well that's great for the daily user. For the monthly user they will
forget that "no news is good news" and should perhaps be told more
explicitly.

OK, now adding -i,
```
Number of files: 1 (reg: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 0
Total file size: 44,983 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 52
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 20
Total bytes received: 63

sent 20 bytes  received 63 bytes  23.71 bytes/sec
total size is 44,983  speedup is 541.96
```

Hard to tell much difference for this one file case.

Anyway, no big deal, but if this was an app made for kids at home,
it would have a big pink balloon "That file is already synced.😼 ".
OK, so there should be a --user-friendly-messages option added,
that when used alone, would dispose of the kilobytes tech stuff,
and just give those human-important messages (perhaps without the "😼".)
