### ISSUE TITLE
setproctitle to include module name

### ISSUE THREAD

**Issue by hloeung** [WayneD/rsync#83]
Hi,

This is more of a wishlist. On a host with multiple rsync modules configured, the process listing looks something like this:

`[module1]`
`  path = ...`
`...`
`[module2]`
`  path = ...`

`root     15749  0.0  0.0  12960   764 ?        Ss   Aug06   1:15 /usr/bin/rsync --daemon --no-detach`
`nobody   10137  0.1  0.0 127508 59168 ?        S    Aug14   3:34  \_ /usr/bin/rsync --daemon --no-detach`
`nobody   13059  0.1  0.0 130536 101228 ?       S    Aug14   5:10  \_ /usr/bin/rsync --daemon --no-detach`
`nobody   54596  0.1  0.0 130536 101248 ?       S    Aug14   4:38  \_ /usr/bin/rsync --daemon --no-detach`
`nobody   28047  0.1  0.0 130536 101248 ?       S    Aug15   4:50  \_ /usr/bin/rsync --daemon --no-detach`

From a process listing, it's hard to tell which rsync child process is associated with which rsync module. I think the only way to achieve that is to have separate users and the module config stanzas so each one uses a separate user.

Would it be possible for rsync children processes to set the process title to include the rsync module?

**Comment by edo1** [comment]
IMO client address could be included as well

**Comment by WayneD** [comment]
There are some drawbacks to setting the process name this way, including leaking secret module names to everyone on the host, cross-os compatibility issues, and having very limited space to put the info (especially on Linux).  Given all that, I'm not inclined to do this.

One alternative is to setup a simple daemon log and grab the info out of that using a script.  For instance, if your rsyncd.conf file contains `log file = /var/log/rsyncd.log` then the attached python3 script would report the pid + module + connecting host info for every active rsync daemon client process. (You'll also need python3-psutil installed.)

[list-rsyncd-clients.txt](https://github.com/WayneD/rsync/files/5270384/list-rsyncd-clients.txt)
