### ISSUE TITLE
Overflow in read_varint()

### ISSUE THREAD

**Issue by sthen** [WayneD/rsync#84]
I have a script that used rsync with local source and both local and remote destination paths, which for simplicity supplied an --rsh option in both cases. Probably as a result of changes in 4f6c8c6652c7, if the option includes the character V this fails:

```
$ rsync --rsh 'V' -r /etc/motd /tmp/
Overflow in read_varint()
rsync error: error in rsync protocol data stream (code 12) at io.c(1747) [sender=3.2.3]
rsync error: received SIGUSR1 (code 19) at main.c(1592) [Receiver=3.2.3]
```

This seems to fix it, but I'm not sure if it's correct:

```
Index: compat.c
--- compat.c.orig
+++ compat.c
@@ -705,7 +705,7 @@ void setup_protocol(int f_out,int f_in)
 				do_negotiated_strings = 1;
 				compat_flags |= CF_VARINT_FLIST_FLAGS;
 			}
-			if (strchr(client_info, 'V') != NULL) { /* Support a pre-release 'V' that got superseded */
+			if (!local_server && strchr(client_info, 'V') != NULL) { /* Support a pre-release 'V' that got superseded */
 				if (!write_batch)
 					compat_flags |= CF_VARINT_FLIST_FLAGS;
 				write_byte(f_out, compat_flags);
```

**Comment by WayneD** [comment]
Yes, that patch is a valid (and simple) way to fix the issue.  I'm opting to fix it in a way that will hopefully avoid future issues in the compat.c code: I checked in a change that gives the local server side a valid client_info string, and then got rid of a bunch of the local_server exceptions.

Thanks for the report!
