### ISSUE TITLE
Does -c actually checksum source and destination file on copy.

### ISSUE THREAD

**Issue by Algajo** [WayneD/rsync#89]
I am working a project where some are doubting the man pages statement that rsync checksums the source and destination files on a copy.  A copy meaning that the destination file does not exist and will always be transmitted.

Can you confirm that the -c checksum does a source and destination checksum happens with this option on a copy as well as a file comparison.

Thanks in advance.  Trying to push some improvements through and really want to put this to bed.

**Comment by WayneD** [comment]
See the [man page](https://download.samba.org/pub/rsync/rsync.1) and search for the --checksum option.  It has a full and accurate discussion about what the option does.
