### ISSUE TITLE
Cross compilation failure during configure - SIMD detection is not working

### ISSUE THREAD

**Issue by epsilon-0** [WayneD/rsync#91]
Cross compiling rsync with SIMD detection causes compilation failure during configuration as the detection uses a C++ program which can't be run while cross compiling

Gentoo bug reported - https://bugs.gentoo.org/732084

**Comment by WayneD** [comment]
I added the action if cross-compiling to AC_RUN_IFELSE() in configure.ac.  The gentoo build rules will need to be sure to run ./prepare-source if they are patching that file so that configure.sh will get the change prior to running configure.
