### ISSUE TITLE
Semantics of --filter

### ISSUE THREAD

**Issue by CL-Jeremy** [WayneD/rsync#94]
Maybe I'm taking it wrong. I'm trying to sync from an SELinux disabled host to an SELinux enabled host. I tried to use `--filter="-xr *"` or `--filter="-xr security.selinux"` without success. What exactly does the combination `xr` do? What could I do to ensure extended attributes get copied and merged into remote (i.e. no remote attributes get deleted during the synchronization)? Thanks in advance.

**Comment by WayneD** [comment]
This is a question for the mailing list, since this is not a bug for the issues tracker.

One thing you might try:

`--filter='-x! user.*'`

If that doesn't work, please send a question to the mailing list.  Thanks!
