### ISSUE TITLE
Error when copying file to existing folder with '--mkpath'

### ISSUE THREAD

**Issue by testplayername** [WayneD/rsync#96]
rsync gives an error when copying a file to an existing folder tree and '--mkpath' is used.

```
$ touch foo
$ mkdir -p sub/dir
$ rsync -ai --mkpath foo sub/dir/bar
rsync: [Receiver] ERROR: cannot stat destination "/tmp/rsync-mkpath-test/sub/dir/bar": File exists (17)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(765) [Receiver=3.2.3]
```
Everything is fine if '--mkpath' is deleted from the last command.

This scenario is similar to this test at https://github.com/WayneD/rsync/blob/01742c07e6d7559d69e101a7c2e5380179c08555/testsuite/mkpath.test

```
# Make sure we can handle an existing path
mkdir $deep_dir/new
$RSYNC -aiv --mkpath from/text $deep_dir/new
test -f $deep_dir/new/text || test_fail "'text' file not found in $deep_dir/new dir"
```

The error code has a file path as source and a file path as destination, whereas the test code in `mkpath.test` has a file path as source and a folder path as destination. The code in `mkpath.test` can be made to give a similar error by changing `$RSYNC -aiv --mkpath from/text $deep_dir/new` to `$RSYNC -aiv --mkpath from/text $deep_dir/new/text`

**Comment by WayneD** [comment]
Thanks! Fixed & test added.
